from typing import List
from aws_cdk import (
    aws_appflow as appflow,
)

from constructs import Construct

class FtSalesforceListingSessionAppFlowTasks(Construct):
    def __init__(self, scope: Construct, id: str) -> None:
        super().__init__(scope, id)

    def get_tasks(self) -> List[appflow.CfnFlow.TaskProperty]:

        tasks = [
            # Task 1: Filter task (PROJECTION)
            appflow.CfnFlow.TaskProperty(
            source_fields=[
                    "Id", "LastModifiedDate", "IsDeleted", "CreatedDate", "Name", "RecordTypeId",
                    "CreatedById", "LastModifiedById", "SystemModstamp", "LastActivityDate", 
                    "LastViewedDate", "LastReferencedDate", "Listing__c", "Actual_Price__c",
                    "Age_Restriction__c", "Base_Price__c", "Brief_Description__c", 
                    "Capacity_Notification_Threshold__c", "Coach_Assigned__c", 
                    "Confirmation_Supporting_Notes__c", "Curriculum_Hours__c", "Event_Coordinator__c",
                    "Full_Description__c", "Gender_Restriction__c", "Listing_Session_Location_Address__c",
                    "Listing_Session_Location_Name__c", "Max_Capacity__c", "Maximum_Age__c",
                    "Membership_Discount_Active__c", "Membership_ID__c", "Membership_Required__c", 
                    "Military_Discount_Active__c", "Minimum_Age__c", "Number_of_Classes__c",
                    "Youth_Serving_Program_Type__c", "Owner__c", "Participants_Reached__c", 
                    "Presented_By__c", "Primary_Image__c", "Primary_Program_Level_Restriction__c", 
                    "Program_Level__c", "Program_Sub_Level__c", "Publish_End_Date_Time__c", 
                    "Publish_Start_Date_Time__c", "Reggie_EventKey__c", "Reggie_EventType__c", 
                    "Reggie_Event_Id__c", "Register_End_Date_Time__c", "Register_Start_Date_Time__c", 
                    "Schedule_Price__c", "Season__c", "Secondary_Program_Level_Restriction__c", 
                    "Session_End_Date_Time__c", "Session_ID__c", "Session_Start_Date_Time__c", 
                    "Session_Status__c", "Sibling_Discount_Active__c", "Support_Coach_1__c", 
                    "Support_Coach_2__c", "Threshold_Notification_Email__c", "Total_Space_Available__c", 
                    "Total_Registrations__c", "Website__c", "Program_Coordinator__c", 
                    "Listing_Session_Location__c", "Presented_By_Name__c", "Region__c", 
                    "Days_Offered__c", "Third_Program_Level_Restriction__c", "Count_Listing_Session__c", 
                    "Priority__c", "Additional_Trade_Name__c", "Can_Be_Registered__c", 
                    "Waitlist_Counter_New__c", "Support_Coach_3_del__c", "Support_Coach_4_del__c", 
                    "Support_Coach_5_del__c", "Support_Coach_6_del__c", "Parent_Communication__c", 
                    "X18_Digit_ID__c", "WaitList_Space_Available__c", "Waitlist_Capacity__c", 
                    "Event_Hours__c", "Session_End_Date__c", "Session_End_Time__c", 
                    "Session_Start_Date__c", "Session_Start_Time__c", "Age_Eligibility_Date__c", 
                    "Allow_Early_Registration__c", "Direct_Session_Link__c", "Private_Event__c", 
                    "Parent_Communication_French__c", "Parent_Communication_Spanish__c", 
                    "Program_Type__c", "Lesson_Plan__c"
                ],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="PROJECTION"
                ),
                task_type="Filter",
                task_properties=[]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Id"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Id",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="id"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="id"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastModifiedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastModifiedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["IsDeleted"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="IsDeleted",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["CreatedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="CreatedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Name"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Name",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["RecordTypeId"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="RecordTypeId",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["CreatedById"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="CreatedById",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastModifiedById"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastModifiedById",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["SystemModstamp"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="SystemModstamp",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastActivityDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastActivityDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastViewedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastViewedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastReferencedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastReferencedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Listing__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Listing__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Actual_Price__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Actual_Price__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="currency"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="currency"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Age_Restriction__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Age_Restriction__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Base_Price__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Base_Price__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="currency"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="currency"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Brief_Description__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Brief_Description__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Capacity_Notification_Threshold__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Capacity_Notification_Threshold__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Coach_Assigned__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Coach_Assigned__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Confirmation_Supporting_Notes__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Confirmation_Supporting_Notes__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Curriculum_Hours__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Curriculum_Hours__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Event_Coordinator__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Event_Coordinator__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Full_Description__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Full_Description__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Gender_Restriction__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Gender_Restriction__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Listing_Session_Location_Address__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Listing_Session_Location_Address__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Listing_Session_Location_Name__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Listing_Session_Location_Name__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Max_Capacity__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Max_Capacity__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Maximum_Age__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Maximum_Age__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Membership_Discount_Active__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Membership_Discount_Active__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Membership_ID__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Membership_ID__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Membership_Required__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Membership_Required__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Military_Discount_Active__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Military_Discount_Active__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Minimum_Age__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Minimum_Age__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Number_of_Classes__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Number_of_Classes__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Youth_Serving_Program_Type__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Youth_Serving_Program_Type__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Owner__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Owner__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Participants_Reached__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Participants_Reached__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Presented_By__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Presented_By__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Primary_Image__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Primary_Image__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Primary_Program_Level_Restriction__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Primary_Program_Level_Restriction__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Program_Level__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Program_Level__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Program_Sub_Level__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Program_Sub_Level__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Publish_End_Date_Time__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Publish_End_Date_Time__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Publish_Start_Date_Time__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Publish_Start_Date_Time__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Reggie_EventKey__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Reggie_EventKey__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Reggie_EventType__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Reggie_EventType__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Reggie_Event_Id__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Reggie_Event_Id__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Register_End_Date_Time__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Register_End_Date_Time__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Register_Start_Date_Time__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Register_Start_Date_Time__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Schedule_Price__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Schedule_Price__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="currency"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="currency"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Season__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Season__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Secondary_Program_Level_Restriction__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Secondary_Program_Level_Restriction__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Session_End_Date_Time__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Session_End_Date_Time__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Session_ID__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Session_ID__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Session_Start_Date_Time__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Session_Start_Date_Time__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Session_Status__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Session_Status__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Sibling_Discount_Active__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Sibling_Discount_Active__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Support_Coach_1__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Support_Coach_1__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Support_Coach_2__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Support_Coach_2__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Threshold_Notification_Email__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Threshold_Notification_Email__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Total_Space_Available__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Total_Space_Available__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Total_Registrations__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Total_Registrations__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Website__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Website__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Program_Coordinator__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Program_Coordinator__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Listing_Session_Location__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Listing_Session_Location__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Presented_By_Name__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Presented_By_Name__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Region__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Region__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Days_Offered__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Days_Offered__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="multipicklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="multipicklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Third_Program_Level_Restriction__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Third_Program_Level_Restriction__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Count_Listing_Session__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Count_Listing_Session__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Priority__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Priority__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Additional_Trade_Name__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Additional_Trade_Name__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Can_Be_Registered__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Can_Be_Registered__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Waitlist_Counter_New__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Waitlist_Counter_New__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Support_Coach_3_del__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Support_Coach_3_del__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Support_Coach_4_del__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Support_Coach_4_del__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Support_Coach_5_del__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Support_Coach_5_del__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Support_Coach_6_del__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Support_Coach_6_del__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Parent_Communication__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Parent_Communication__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["X18_Digit_ID__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="X18_Digit_ID__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["WaitList_Space_Available__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="WaitList_Space_Available__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Waitlist_Capacity__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Waitlist_Capacity__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Event_Hours__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Event_Hours__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Session_End_Date__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Session_End_Date__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Session_End_Time__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Session_End_Time__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="time"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="time"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Session_Start_Date__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Session_Start_Date__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Session_Start_Time__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Session_Start_Time__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="time"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="time"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Age_Eligibility_Date__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Age_Eligibility_Date__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Allow_Early_Registration__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Allow_Early_Registration__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Direct_Session_Link__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Direct_Session_Link__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Private_Event__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Private_Event__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Parent_Communication_French__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Parent_Communication_French__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Parent_Communication_Spanish__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Parent_Communication_Spanish__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Program_Type__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Program_Type__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Lesson_Plan__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Lesson_Plan__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="url"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="url"
                    )
                ]
            )
        ]


        return tasks







