from typing import List
from aws_cdk import (
    aws_appflow as appflow,
)
from constructs import Construct

class FtSalesforceBadgeAppFlowTasks(Construct):
    def __init__(self, scope: Construct, id: str) -> None:
        super().__init__(scope, id)



    def get_tasks(self)-> List[appflow.CfnFlow.TaskProperty]:
        tasks: List[appflow.CfnFlow.TaskProperty] = [
            appflow.CfnFlow.TaskProperty(
                source_fields=[
                    "Id",
                    "OwnerId",
                    "IsDeleted", 
                    "Name",
                    "CreatedDate", 
                    "CreatedById", 
                    "LastModifiedDate", 
                    "LastModifiedById", 
                    "SystemModstamp",
                    "LastViewedDate", 
                    "LastReferencedDate", 
                    "Category__c", 
                    "Description__c", 
                    "Badge_Type__c", 
                    "Coaches_App_Image_Id__c"
                    "Coaches_App_Image_URL__c",
                    "Is_Active__c",
                    "Parent_Registration_Image_Id__c",
                    "Parent_Registration_Image_URL__c",
                    "Points__c",
                    "Sort_Order__c",
                    "badge_id__c",
                    "Age_Group__c"
        ],

        connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="PROJECTION"
                ),
                task_type="Filter",
                task_properties=[]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Id"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Id",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="id"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="id"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["OwnerId"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="OwnerId",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["IsDeleted"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="IsDeleted",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Name"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Name",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["CreatedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="CreatedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
              appflow.CfnFlow.TaskProperty(
                source_fields=["LastModifiedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastModifiedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastModifiedById"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastModifiedById",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["SystemModstamp"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="SystemModstamp",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastViewedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastViewedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastReferencedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastReferencedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Category__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Category__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Description__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Description__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Badge_Type__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Badge_Type__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Coaches_App_Image_Id__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Coaches_App_Image_Id__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Coaches_App_Image_URL__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Coaches_App_Image_URL__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
            source_fields=["Is_Active__c"],
            connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
            destination_field="Is_Active__c",
            task_type="Map",
            task_properties=[
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="DESTINATION_DATA_TYPE",
                    value="boolean"
                ),
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="SOURCE_DATA_TYPE",
                    value="boolean"
                )
            ]
        ),
        appflow.CfnFlow.TaskProperty(
            source_fields=["Parent_Registration_Image_Id__c"],
            connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
            destination_field="Parent_Registration_Image_Id__c",
            task_type="Map",
            task_properties=[
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="DESTINATION_DATA_TYPE",
                    value="string"
                ),
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="SOURCE_DATA_TYPE",
                    value="string"
                )
            ]
        ),
        appflow.CfnFlow.TaskProperty(
            source_fields=["Parent_Registration_Image_URL__c"],
            connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
            destination_field="Parent_Registration_Image_URL__c",
            task_type="Map",
            task_properties=[
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="DESTINATION_DATA_TYPE",
                    value="string"
                ),
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="SOURCE_DATA_TYPE",
                    value="string"
                )
            ]
        ),
        appflow.CfnFlow.TaskProperty(
            source_fields=["Points__c"],
            connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
            destination_field="Points__c",
            task_type="Map",
            task_properties=[
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="DESTINATION_DATA_TYPE",
                    value="double"
                ),
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="SOURCE_DATA_TYPE",
                    value="double"
                )
            ]
        ),
        appflow.CfnFlow.TaskProperty(
            source_fields=["Sort_Order__c"],
            connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
            destination_field="Sort_Order__c",
            task_type="Map",
            task_properties=[
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="DESTINATION_DATA_TYPE",
                    value="double"
                ),
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="SOURCE_DATA_TYPE",
                    value="double"
                )
            ]
        ),
        appflow.CfnFlow.TaskProperty(
            source_fields=["badge_id__c"],
            connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
            destination_field="badge_id__c",
            task_type="Map",
            task_properties=[
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="DESTINATION_DATA_TYPE",
                    value="string"
                ),
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="SOURCE_DATA_TYPE",
                    value="string"
                )
            ]
        ),
        appflow.CfnFlow.TaskProperty(
            source_fields=["Age_Group__c"],
            connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
            destination_field="Age_Group__c",
            task_type="Map",
            task_properties=[
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="DESTINATION_DATA_TYPE",
                    value="picklist"
                ),
                appflow.CfnFlow.TaskPropertiesObjectProperty(
                    key="SOURCE_DATA_TYPE",
                    value="picklist"
                )
            ]
        ),
        ]

        return tasks







