from typing import List
from aws_cdk import (
    aws_appflow as appflow,
)
from constructs import Construct

class FtSalesforceAccountAppFlowTasks(Construct):
    def __init__(self, scope: Construct, id: str) -> None:
        super().__init__(scope, id)

    def get_tasks(self) -> List[appflow.CfnFlow.TaskProperty]:

        full_field_mappings = [
            {"sourceField": "Id", "destinationField": "Id", "sourceDataType": "id", "destinationDataType": "id"},
            {"sourceField": "IsDeleted", "destinationField": "IsDeleted", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "MasterRecordId", "destinationField": "MasterRecordId", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "Name", "destinationField": "Name", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Type", "destinationField": "Type", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "RecordTypeId", "destinationField": "RecordTypeId", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "ParentId", "destinationField": "ParentId", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "BillingStreet", "destinationField": "BillingStreet", "sourceDataType": "textarea", "destinationDataType": "textarea"},
            {"sourceField": "BillingCity", "destinationField": "BillingCity", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "BillingState", "destinationField": "BillingState", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "BillingPostalCode", "destinationField": "BillingPostalCode", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "BillingCountry", "destinationField": "BillingCountry", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "BillingAddress", "destinationField": "BillingAddress", "sourceDataType": "address", "destinationDataType": "address"},
            {"sourceField": "ShippingStreet", "destinationField": "ShippingStreet", "sourceDataType": "textarea", "destinationDataType": "textarea"},
            {"sourceField": "ShippingCity", "destinationField": "ShippingCity", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "ShippingState", "destinationField": "ShippingState", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "ShippingPostalCode", "destinationField": "ShippingPostalCode", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "ShippingCountry", "destinationField": "ShippingCountry", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "ShippingAddress", "destinationField": "ShippingAddress", "sourceDataType": "address", "destinationDataType": "address"},
            {"sourceField": "Phone", "destinationField": "Phone", "sourceDataType": "phone", "destinationDataType": "phone"},
            {"sourceField": "AccountNumber", "destinationField": "AccountNumber", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Website", "destinationField": "Website", "sourceDataType": "url", "destinationDataType": "url"},
            {"sourceField": "NumberOfEmployees", "destinationField": "NumberOfEmployees", "sourceDataType": "int", "destinationDataType": "int"},
            {"sourceField": "Ownership", "destinationField": "Ownership", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Description", "destinationField": "Description", "sourceDataType": "textarea", "destinationDataType": "textarea"},
            {"sourceField": "OwnerId", "destinationField": "OwnerId", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "CreatedDate", "destinationField": "CreatedDate", "sourceDataType": "datetime", "destinationDataType": "datetime"},
            {"sourceField": "CreatedById", "destinationField": "CreatedById", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "LastModifiedDate", "destinationField": "LastModifiedDate", "sourceDataType": "datetime", "destinationDataType": "datetime"},
            {"sourceField": "LastModifiedById", "destinationField": "LastModifiedById", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "SystemModstamp", "destinationField": "SystemModstamp", "sourceDataType": "datetime", "destinationDataType": "datetime"},
            {"sourceField": "LastActivityDate", "destinationField": "LastActivityDate", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "LastViewedDate", "destinationField": "LastViewedDate", "sourceDataType": "datetime", "destinationDataType": "datetime"},
            {"sourceField": "LastReferencedDate", "destinationField": "LastReferencedDate", "sourceDataType": "datetime", "destinationDataType": "datetime"},
            {"sourceField": "IsPartner", "destinationField": "IsPartner", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "IsCustomerPortal", "destinationField": "IsCustomerPortal", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "ChannelProgramName", "destinationField": "ChannelProgramName", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "ChannelProgramLevelName", "destinationField": "ChannelProgramLevelName", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Chapter_Administrator__c", "destinationField": "Chapter_Administrator__c", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "Chapter_Affiliation__c", "destinationField": "Chapter_Affiliation__c", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "Territory__c", "destinationField": "Territory__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Chapter_ID__c", "destinationField": "Chapter_ID__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Membership_Offered__c", "destinationField": "Membership_Offered__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Payments_Accepted_In_Person__c", "destinationField": "Payments_Accepted_In_Person__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Time_Zone__c", "destinationField": "Time_Zone__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Coach_Retention_Rate__c", "destinationField": "Coach_Retention_Rate__c", "sourceDataType": "percent", "destinationDataType": "percent"},
            {"sourceField": "Count_Account__c", "destinationField": "Count_Account__c", "sourceDataType": "double", "destinationDataType": "double"},
            {"sourceField": "Current_Coach_Retention_Percentage__c", "destinationField": "Current_Coach_Retention_Percentage__c", "sourceDataType": "percent", "destinationDataType": "percent"},
            {"sourceField": "Performance_Record_Type__c", "destinationField": "Performance_Record_Type__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "YS_Report_Chapter_Affiliation__c", "destinationField": "YS_Report_Chapter_Affiliation__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Insurance_Expires__c", "destinationField": "Insurance_Expires__c", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "Affiliate_Delivery_Partner__c", "destinationField": "Affiliate_Delivery_Partner__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Date_Joined__c", "destinationField": "Date_Joined__c", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "Equipment__c", "destinationField": "Equipment__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Graduate__c", "destinationField": "Graduate__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Home_School__c", "destinationField": "Home_School__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Kindergarten__c", "destinationField": "Kindergarten__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Account_ID__c", "destinationField": "Account_ID__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Additional_Trade_NameChap_Affiliation__c", "destinationField": "Additional_Trade_NameChap_Affiliation__c", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "Additional_Trade_Name_Logo__c", "destinationField": "Additional_Trade_Name_Logo__c", "sourceDataType": "textarea", "destinationDataType": "textarea"},
            {"sourceField": "Parent_Account_ID_18__c", "destinationField": "Parent_Account_ID_18__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Account_Inactive_Date__c", "destinationField": "Account_Inactive_Date__c", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "Legacy_ID__c", "destinationField": "Legacy_ID__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "EIN__c", "destinationField": "EIN__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Governance_Structure__c", "destinationField": "Governance_Structure__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Youth_Population__c", "destinationField": "Youth_Population__c", "sourceDataType": "double", "destinationDataType": "double"},
            {"sourceField": "Contract_Effective_Date__c", "destinationField": "Contract_Effective_Date__c", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "Active__c", "destinationField": "Active__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Chapter_Membership_Price__c", "destinationField": "Chapter_Membership_Price__c", "sourceDataType": "currency", "destinationDataType": "currency"},
            {"sourceField": "Chapter_Standing__c", "destinationField": "Chapter_Standing__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Contract_Expiration_Date__c", "destinationField": "Contract_Expiration_Date__c", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "Contract_Status__c", "destinationField": "Contract_Status__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "County__c", "destinationField": "County__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "HO_Contracted_Location__c", "destinationField": "HO_Contracted_Location__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Inactive_Date__c", "destinationField": "Inactive_Date__c", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "Legal_Entity_Name__c", "destinationField": "Legal_Entity_Name__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Membership_Active__c", "destinationField": "Membership_Active__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Membership_Discount_Amount__c", "destinationField": "Membership_Discount_Amount__c", "sourceDataType": "currency", "destinationDataType": "currency"},
            {"sourceField": "Membership_Discount_Percentage__c", "destinationField": "Membership_Discount_Percentage__c", "sourceDataType": "percent", "destinationDataType": "percent"},
            {"sourceField": "Membership_End_Date__c", "destinationField": "Membership_End_Date__c", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "Membership_Start_Date__c", "destinationField": "Membership_Start_Date__c", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "Military_Discount_Amount__c", "destinationField": "Military_Discount_Amount__c", "sourceDataType": "currency", "destinationDataType": "currency"},
            {"sourceField": "Military_Discount_Percentage__c", "destinationField": "Military_Discount_Percentage__c", "sourceDataType": "percent", "destinationDataType": "percent"},
            {"sourceField": "Primary_Contact_Email__c", "destinationField": "Primary_Contact_Email__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Primary_Contact__c", "destinationField": "Primary_Contact__c", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "Primary_Contact_email_address__c", "destinationField": "Primary_Contact_email_address__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Program_Location_Key__c", "destinationField": "Program_Location_Key__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Program_Location_Type__c", "destinationField": "Program_Location_Type__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Reggie_Account_Id__c", "destinationField": "Reggie_Account_Id__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Reggie_Id__c", "destinationField": "Reggie_Id__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Reggie_Location_Id__c", "destinationField": "Reggie_Location_Id__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Reggie_Name__c", "destinationField": "Reggie_Name__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Region__c", "destinationField": "Region__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Secondary_Contact__c", "destinationField": "Secondary_Contact__c", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "Location_Type__c", "destinationField": "Location_Type__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Sibling_Discount_Amount__c", "destinationField": "Sibling_Discount_Amount__c", "sourceDataType": "currency", "destinationDataType": "currency"},
            {"sourceField": "Sibling_Discount_Percentage__c", "destinationField": "Sibling_Discount_Percentage__c", "sourceDataType": "percent", "destinationDataType": "percent"},
            {"sourceField": "Service_Area__c", "destinationField": "Service_Area__c", "sourceDataType": "textarea", "destinationDataType": "textarea"},
            {"sourceField": "Insurance_Expiration_Date__c", "destinationField": "Insurance_Expiration_Date__c", "sourceDataType": "date", "destinationDataType": "date"},
            {"sourceField": "Former_Trade_Names__c", "destinationField": "Former_Trade_Names__c", "sourceDataType": "textarea", "destinationDataType": "textarea"},
            {"sourceField": "Former_Legal_Entity__c", "destinationField": "Former_Legal_Entity__c", "sourceDataType": "textarea", "destinationDataType": "textarea"},
            {"sourceField": "Organization_City__c", "destinationField": "Organization_City__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Organization_State__c", "destinationField": "Organization_State__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Partner_Program_Type__c", "destinationField": "Partner_Program_Type__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Pre_School__c", "destinationField": "Pre_School__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Status__c", "destinationField": "Status__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Title_I__c", "destinationField": "Title_I__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Enrollment__c", "destinationField": "Enrollment__c", "sourceDataType": "double", "destinationDataType": "double"},
            {"sourceField": "Market_Size__c", "destinationField": "Market_Size__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "DCR__c", "destinationField": "DCR__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Owner_ID__c", "destinationField": "Owner_ID__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Program_Director__c", "destinationField": "Program_Director__c", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "Executive_Director__c", "destinationField": "Executive_Director__c", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "Board_Chair__c", "destinationField": "Board_Chair__c", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "MDR_PID__c", "destinationField": "MDR_PID__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Partner_Program_Type_Validation_Check__c", "destinationField": "Partner_Program_Type_Validation_Check__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Duplicates_Removed__c", "destinationField": "Duplicates_Removed__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "NCES_ID__c", "destinationField": "NCES_ID__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Currency__c", "destinationField": "Currency__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Territory_Partner_Acct__c", "destinationField": "Territory_Partner_Acct__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Chapter_Country__c", "destinationField": "Chapter_Country__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Financial_Aid_Active__c", "destinationField": "Financial_Aid_Active__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "New_Parent_Registration__c", "destinationField": "New_Parent_Registration__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Additional_Trade_Name__c", "destinationField": "Additional_Trade_Name__c", "sourceDataType": "reference", "destinationDataType": "reference"},
            {"sourceField": "FT_App_Pilot__c", "destinationField": "FT_App_Pilot__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "International_Chapter__c", "destinationField": "International_Chapter__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Customer_ID__c", "destinationField": "Customer_ID__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Award_Badges_Enabled__c", "destinationField": "Award_Badges_Enabled__c", "sourceDataType": "boolean", "destinationDataType": "boolean"},
            {"sourceField": "Peer_Group__c", "destinationField": "Peer_Group__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "In_Market_Partners__c", "destinationField": "In_Market_Partners__c", "sourceDataType": "multipicklist", "destinationDataType": "multipicklist"},
            {"sourceField": "How_many_holes__c", "destinationField": "How_many_holes__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "If_other_fill_in_how_many__c", "destinationField": "If_other_fill_in_how_many__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Golf_Course_Type__c", "destinationField": "Golf_Course_Type__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Course_Features_available_to_First_Tee__c", "destinationField": "Course_Features_available_to_First_Tee__c", "sourceDataType": "multipicklist", "destinationDataType": "multipicklist"},
            {"sourceField": "Does_the_facility_offer_discounts_to_Fir__c", "destinationField": "Does_the_facility_offer_discounts_to_Fir__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Please_describe_discount__c", "destinationField": "Please_describe_discount__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Chapter_owns_this_facility__c", "destinationField": "Chapter_owns_this_facility__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Operates_the_facility_through_a_lease__c", "destinationField": "Operates_the_facility_through_a_lease__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "If_yes_how_long_is_the_lease__c", "destinationField": "If_yes_how_long_is_the_lease__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Who_is_the_lease_with__c", "destinationField": "Who_is_the_lease_with__c", "sourceDataType": "string", "destinationDataType": "string"},
            {"sourceField": "Notes_about_the_partnership__c", "destinationField": "Notes_about_the_partnership__c", "sourceDataType": "textarea", "destinationDataType": "textarea"},
            {"sourceField": "Does_this_facility_have_a_dedicated_Firs__c", "destinationField": "Does_this_facility_have_a_dedicated_Firs__c", "sourceDataType": "picklist", "destinationDataType": "picklist"},
            {"sourceField": "Please_describe_the_learning_center__c", "destinationField": "Please_describe_the_learning_center__c", "sourceDataType": "picklist", "destinationDataType": "picklist"}
        ]

        tasks: List[appflow.CfnFlow.TaskProperty] = [
            appflow.CfnFlow.TaskProperty(
                source_fields=[mapping["sourceField"]],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field=mapping["destinationField"],
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(key="DESTINATION_DATA_TYPE", value=mapping["destinationDataType"]),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(key="SOURCE_DATA_TYPE", value=mapping["sourceDataType"]),
                ]
            ) for mapping in full_field_mappings
        ]

        return tasks
