from typing import List
from aws_cdk import (
    aws_appflow as appflow,
)

from constructs import Construct

class FtSalesforceListingAppFlowTasks(Construct):
    def __init__(self, scope: Construct, id: str) -> None:
        super().__init__(scope, id)

    def get_tasks(self) -> List[appflow.CfnFlow.TaskProperty]:
        tasks: List[appflow.CfnFlow.TaskProperty] = [
            appflow.CfnFlow.TaskProperty(
                source_fields=[
                    "Id",
                    "LastModifiedDate",
                    "IsDeleted",
                    "CreatedDate",
                    "Name",
                    "RecordTypeId",
                    "CreatedById",
                    "LastModifiedById",
                    "SystemModstamp",
                    "LastActivityDate",
                    "LastViewedDate",
                    "LastReferencedDate",
                    "Brief_Description__c",
                    "Full_Description__c",
                    "Membership_Discount_Active__c",
                    "Military_Discount_Active__c",
                    "Presented_By__c",
                    "Primary_Image__c",
                    "Sibling_Discount_Active__c",
                    "Priority__c",
                    "OwnerId",
                    "Account__c",
                    "Class_ID__c",
                    "Class_Status__c",
                    "End_Date__c",
                    "Event_ID__c",
                    "Event_Status__c",
                    "External_ID__c",
                    "Hosted_By__c",
                    "Is_Public__c",
                    "Listing_Location_Address__c",
                    "Publish_End_Date__c",
                    "Publish_Start_Date__c",
                    "Return_Policy__c",
                    "Start_Date__c",
                    "Total_Coaches__c",
                    "test__c",
                    "Count_Listing__c"
                ],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="PROJECTION"
                ),
                task_type="Filter",
                task_properties=[]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Id"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Id",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="id"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="id"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastModifiedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastModifiedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["IsDeleted"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="IsDeleted",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["CreatedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="CreatedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Name"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Name",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["RecordTypeId"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="RecordTypeId",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["CreatedById"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="CreatedById",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastModifiedById"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastModifiedById",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["SystemModstamp"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="SystemModstamp",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastActivityDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastActivityDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastViewedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastViewedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastReferencedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="LastReferencedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Brief_Description__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Brief_Description__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Full_Description__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Full_Description__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Membership_Discount_Active__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Membership_Discount_Active__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Military_Discount_Active__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Military_Discount_Active__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Presented_By__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Presented_By__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Primary_Image__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Primary_Image__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Sibling_Discount_Active__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Sibling_Discount_Active__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Priority__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Priority__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["OwnerId"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="OwnerId",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Account__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Account__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Class_ID__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Class_ID__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Class_Status__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Class_Status__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["End_Date__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="End_Date__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Event_ID__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Event_ID__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Event_Status__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Event_Status__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["External_ID__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="External_ID__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Hosted_By__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Hosted_By__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Is_Public__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Is_Public__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Listing_Location_Address__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Listing_Location_Address__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Publish_End_Date__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Publish_End_Date__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Publish_Start_Date__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Publish_Start_Date__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Return_Policy__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Return_Policy__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Start_Date__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Start_Date__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Total_Coaches__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Total_Coaches__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["test__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="test__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    )
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Count_Listing__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(salesforce="NO_OP"),
                destination_field="Count_Listing__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            )
        ]

        return tasks







