from typing import List
from aws_cdk import (
    aws_appflow as appflow,
)

from constructs import Construct

class FtSalesforceContactAppFlowTasks(Construct):
    def __init__(self, scope: Construct, id: str) -> None:
        super().__init__(scope, id)

    def get_tasks(self) -> List[appflow.CfnFlow.TaskProperty]:
        tasks: List[appflow.CfnFlow.TaskProperty] = [
            appflow.CfnFlow.TaskProperty(
                source_fields=[
                    "Id", "Chapter_Affiliation__c", "ChapterID_CONTACT__c", "CASESAFEID__c",
                    "Contact_Type__c", "Age__c", "Ethnicity__c", "Gender__c", "Grade__c",
                    "Participation_Status__c", "MailingPostalCode", "MailingStreet",
                    "MailingCity", "MailingState", "School_Name__c", "School_Name_Other__c",
                    "FirstName", "LastName", "Birthdate", "AccountId", "LastModifiedDate",
                    "IsDeleted", "CreatedDate", "SystemModstamp"
                ],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="PROJECTION"
                ),
                task_type="Filter",
                task_properties=[]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Id"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Id",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="id"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="id"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Chapter_Affiliation__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Chapter_Affiliation__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["ChapterID_CONTACT__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="ChapterID_CONTACT__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["CASESAFEID__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="CASESAFEID__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Contact_Type__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Contact_Type__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="multipicklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="multipicklist"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Age__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Age__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Ethnicity__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Ethnicity__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Gender__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Gender__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Grade__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Grade__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Participation_Status__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Participation_Status__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["MailingPostalCode"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="MailingPostalCode",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["MailingStreet"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="MailingStreet",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="textarea"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="textarea"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["MailingCity"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="MailingCity",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["MailingState"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="MailingState",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["School_Name__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="School_Name__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["School_Name_Other__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="School_Name_Other__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["FirstName"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="FirstName",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastName"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="LastName",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["Birthdate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Birthdate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["AccountId"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="AccountId",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastModifiedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="LastModifiedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["IsDeleted"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="IsDeleted",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["CreatedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="CreatedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    ),
                ]
            ),
            appflow.CfnFlow.TaskProperty(
                source_fields=["SystemModstamp"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="SystemModstamp",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    ),
                ]
            )
        ]

        return tasks







