from typing import List
from aws_cdk import (
    aws_appflow as appflow,
)

from constructs import Construct

class FtSalesforceWaitlistAppFlowTasks(Construct):
    def __init__(self, scope: Construct, id: str) -> None:
        super().__init__(scope, id)

    def get_tasks(self) -> List[appflow.CfnFlow.TaskProperty]:
        tasks: List[appflow.CfnFlow.TaskProperty] = [
            appflow.CfnFlow.TaskProperty(
                source_fields= ["Chapter_Name__c", 
                                "ChapterId__c", 
                                "Contact__c", 
                                "Created_By_Email__c", 
                                "CreatedById",
                                "CreatedDate", 
                                "IsDeleted", 
                                "LastModifiedById", 
                                "LastModifiedDate",
                                "LastActivityDate", 
                                "LastViewedDate", 
                                "LastReferencedDate",
                                "Listing_Session__c",
                                "Listing_Session_Location_Address__c", 
                                "Listing_Session_Location_Name__c",
                                "Listing_Session_Name__c",
                                "Membership_End_Date__c" , 
                                "Membership_Price__c", 
                                "Membership_Required__c", 
                                "Membership_Start_Date__c", 
                                "Parent_Contact__c", 
                                "Id", 
                                "Status__c", 
                                "SystemModstamp",
                                "Name", 
                                "Waitlist_Participant_order__c",
                                "Waitlist_Unique_Key__c",
                                "Status_Is_In_Process_or_Selected__c"
                                ],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="PROJECTION"
                ),
                task_type="Filter",
                task_properties=[] 
                ), 
            # Mapping tasks for each field
            appflow.CfnFlow.TaskProperty(
                source_fields=["Id"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Id",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="id"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="id"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["IsDeleted"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="IsDeleted",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Name"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Name",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["CreatedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="CreatedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["CreatedById"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="CreatedById",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastModifiedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="LastModifiedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastModifiedById"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="LastModifiedById",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["SystemModstamp"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="SystemModstamp",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastActivityDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="LastActivityDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastViewedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="LastViewedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["LastReferencedDate"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="LastReferencedDate",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="datetime"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="datetime"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Listing_Session__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Listing_Session__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["ChapterId__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="ChapterId__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Chapter_Name__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Chapter_Name__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Contact__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Contact__c",
                task_type="Map",
                  task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Listing_Session_Location_Address__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Listing_Session_Location_Address__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Listing_Session_Location_Name__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Listing_Session_Location_Name__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Listing_Session_Name__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Listing_Session_Name__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Membership_End_Date__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Membership_End_Date__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Membership_Price__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Membership_Price__c",
                task_type="Map",
                 task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="currency"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="currency"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Membership_Required__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Membership_Required__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="boolean"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="boolean"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Membership_Start_Date__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Membership_Start_Date__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="date"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="date"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Parent_Contact__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Parent_Contact__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="reference"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="reference"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Status__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Status__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="picklist"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="picklist"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Waitlist_Participant_order__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Waitlist_Participant_order__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="double"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="double"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Created_By_Email__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Created_By_Email__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Waitlist_Unique_Key__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Waitlist_Unique_Key__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            ),
            
            appflow.CfnFlow.TaskProperty(
                source_fields=["Status_Is_In_Process_or_Selected__c"],
                connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(
                    salesforce="NO_OP"
                ),
                destination_field="Status_Is_In_Process_or_Selected__c",
                task_type="Map",
                task_properties=[
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="DESTINATION_DATA_TYPE",
                        value="string"
                    ),
                    appflow.CfnFlow.TaskPropertiesObjectProperty(
                        key="SOURCE_DATA_TYPE",
                        value="string"
                    )
                ]
            )
        ]
    
        return tasks
