-- --sf_metric_historical_ethnic_diversity_percentage various data models
-- --
-- CREATE TABLE IF NOT EXISTS ft_ds_refined.sf_metric_historical_ethnic_diversity_percentage (
--     snapshot_date TIMESTAMPTZ,
--     ethnic_diversity_percentage NUMERIC
-- );

-- --this can also be string to keep it more flexible
-- CREATE TYPE ethnicity_dtype as ENUM (
--     'Asian',
--     'Black or African-American',
--     'Multi-Racial',
--     'Native American or Native Alaskan',
--     'Pacific Islander',
--     'White or Caucasian', 
--     'Prefer not to respond'
-- );
-- CREATE TABLE IF NOT EXISTS ft_ds_refined.sf_metric_historical_ethnic_breakdown (
--     snapshot_date TIMESTAMPTZ,
--     ethnicity VARCHAR(100),
--     ethnically_diverse BOOLEAN,
--     participant_count INTEGER
-- );

-- CREATE TABLE IF NOT EXISTS ft_ds_refined.sf_metric_historical_ethnic_breakdown (
--     snapshot_date TIMESTAMPTZ,
--     asian_count INTEGER,
--     black_or_african_american_count INTEGER,
--     multi_racial_count INTEGER,
--     native_american_or_native_alaskan_count INTEGER,
--     pacific_islander_count INTEGER,
--     white_or_caucasian_count INTEGER,
--     prefer_not_to_respond_count INTEGER,
--     --can also just be these two
--     ethnically_diverse_count INTEGER,
--     total_count INTEGER

-- )