CREATE OR REPLACE VIEW ft_ds_refined.chapter_account_view
AS
SELECT
    account_name,
    legal_entity_name,
    board_chair,
    executive_director,
    program_director_id,
    payments_accepted_in_person,
    --NOT IN RAW AS sfdc_go_live_date,
    international_chapter,
    ft_app_pilot,
    --NOT IN VALID AS award_badges_enabled,
    account_record_type_id,
    is_active,
    contract_status,
    contract_effective_date,
    contract_expiration_date,
    insurance_expiration_date,
    dcr,
    territory,
    peer_group AS peer_group_level,
    governance_structure,
    service_area,
    youth_population,
    chapter_standing,
    former_trade_names,
    former_legal_entity,
    partners_in_market,
    --NOT IN RAW AS payment_provider,
    billing_street,
    billing_city,
    billing_state,
    billing_postal_code,
    billing_country,
    shipping_street,
    shipping_city,
    shipping_state,
    shipping_postal_code,
    shipping_country,
    --NOT IN RAW AS county,
    membership_offered,
    membership_active,
    chapter_membership_price,
    membership_start_date,
    membership_end_date,
    membership_discount_amount,
    membership_discount_percentage,
    sibling_discount_amount,
    sibling_discount_percentage,
    military_discount_amount,
    military_discount_percentage,
    account_inactive_date,
    time_zone,
    new_parent_registration,
    ys_report_chapter_affiliation,
    account_id,
    reggie_name,
    --NOT IN RAW AS fmp_id,
    --NOT IN RAW AS fmp_chapter_code,
    --NOT IN RAW AS mrm_id,
    --NOT IN RAW AS legacy_account_holder_id,
    --NOT IN RAW AS legacy_participant_user_id,
    reggie_location_id,
    reggie_account_id,
    reggie_id
-- ommitted the is_deleted field since it is an unanalyzable metadata field.
FROM ft_ds_refined.account
WHERE
    account_record_type_id = '01236000000nmeEAAQ'
;