from data_core.salesforce.account.sf_account_db_models import SfAccountRawDbModel, SfAccountSourceModel, map_account_sources_to_raws
from psycopg2.extensions import connection
from datetime import datetime

from typing import List

import logging

class SalesforceAccountDbHelper:

    @staticmethod
    def insert_sf_raw_account(*, 
                            db_connection: connection, 
                            new_raw_account: List[SfAccountRawDbModel],
                            commit_changes: bool = True):
        """
        Inserts a collection of SfAccountRawDbModel objects into PostgreSQL.
        If a primary key violation occurs, updates the conflicting record.
        
        Args:
        - new_raw_account: List of SfAccountRawDbModel instances.
        - db_connection: A pre-existing psycopg2 connection object.
        - commit_changes: Boolean to determine if changes should be committed.
        """
        # Use the provided connection to create a cursor
        cursor = db_connection.cursor()
        
        upsert_query = """                  
        INSERT INTO ft_ds_raw.sf_account (
            id, isdeleted, masterrecordid, name, type, recordtypeid, parentid, billingstreet, billingcity, billingstate,
            billingpostalcode, billingcountry, billingaddress, shippingstreet, shippingcity, shippingstate,
            shippingpostalcode, shippingcountry, shippingaddress, phone, accountnumber, website, numberofemployees,
            ownership, description, ownerid, createddate, createdbyid, lastmodifieddate, lastmodifiedbyid,
            systemmodstamp, lastactivitydate, lastvieweddate, lastreferenceddate, ispartner, iscustomerportal,
            channelprogramname, channelprogramlevelname, chapter_administrator__c, chapter_affiliation__c,
            territory__c, chapter_id__c, membership_offered__c, payments_accepted_in_person__c, time_zone__c,
            coach_retention_rate__c, count_account__c, current_coach_retention_percentage__c,
            performance_record_type__c, ys_report_chapter_affiliation__c, insurance_expires__c,
            affiliate_delivery_partner__c, date_joined__c, equipment__c, graduate__c, home_school__c,
            kindergarten__c, account_id__c, additional_trade_namechap_affiliation__c, additional_trade_name_logo__c,
            parent_account_id_18__c, account_inactive_date__c, legacy_id__c, ein__c, governance_structure__c,
            youth_population__c, contract_effective_date__c, active__c, chapter_membership_price__c,
            chapter_standing__c, contract_expiration_date__c, contract_status__c, county__c,
            ho_contracted_location__c, inactive_date__c, legal_entity_name__c, membership_active__c,
            membership_discount_amount__c, membership_discount_percentage__c, membership_end_date__c,
            membership_start_date__c, military_discount_amount__c, military_discount_percentage__c,
            primary_contact_email__c, primary_contact__c, primary_contact_email_address__c,
            program_location_key__c, program_location_type__c, reggie_account_id__c, reggie_id__c,
            reggie_location_id__c, reggie_name__c, region__c, secondary_contact__c, location_type__c,
            sibling_discount_amount__c, sibling_discount_percentage__c, service_area__c,
            insurance_expiration_date__c, former_trade_names__c, former_legal_entity__c,
            organization_city__c, organization_state__c, partner_program_type__c,dss_ingestion_timestamp
        ) VALUES (
            %(id)s, %(isdeleted)s, %(masterrecordid)s, %(name)s, %(type)s, %(recordtypeid)s, %(parentid)s,
            %(billingstreet)s, %(billingcity)s, %(billingstate)s, %(billingpostalcode)s, %(billingcountry)s,
            %(billingaddress)s, %(shippingstreet)s, %(shippingcity)s, %(shippingstate)s, %(shippingpostalcode)s,
            %(shippingcountry)s, %(shippingaddress)s, %(phone)s, %(accountnumber)s, %(website)s,
            %(numberofemployees)s, %(ownership)s, %(description)s, %(ownerid)s, %(createddate)s, %(createdbyid)s,
            %(lastmodifieddate)s, %(lastmodifiedbyid)s, %(systemmodstamp)s, %(lastactivitydate)s,
            %(lastvieweddate)s, %(lastreferenceddate)s, %(ispartner)s, %(iscustomerportal)s,
            %(channelprogramname)s, %(channelprogramlevelname)s, %(chapter_administrator__c)s,
            %(chapter_affiliation__c)s, %(territory__c)s, %(chapter_id__c)s, %(membership_offered__c)s,
            %(payments_accepted_in_person__c)s, %(time_zone__c)s, %(coach_retention_rate__c)s,
            %(count_account__c)s, %(current_coach_retention_percentage__c)s, %(performance_record_type__c)s,
            %(ys_report_chapter_affiliation__c)s, %(insurance_expires__c)s, %(affiliate_delivery_partner__c)s,
            %(date_joined__c)s, %(equipment__c)s, %(graduate__c)s, %(home_school__c)s, %(kindergarten__c)s,
            %(account_id__c)s, %(additional_trade_namechap_affiliation__c)s, %(additional_trade_name_logo__c)s,
            %(parent_account_id_18__c)s, %(account_inactive_date__c)s, %(legacy_id__c)s, %(ein__c)s,
            %(governance_structure__c)s, %(youth_population__c)s, %(contract_effective_date__c)s, %(active__c)s,
            %(chapter_membership_price__c)s, %(chapter_standing__c)s, %(contract_expiration_date__c)s,
            %(contract_status__c)s, %(county__c)s, %(ho_contracted_location__c)s, %(inactive_date__c)s,
            %(legal_entity_name__c)s, %(membership_active__c)s, %(membership_discount_amount__c)s,
            %(membership_discount_percentage__c)s, %(membership_end_date__c)s, %(membership_start_date__c)s,
            %(military_discount_amount__c)s, %(military_discount_percentage__c)s, %(primary_contact_email__c)s,
            %(primary_contact__c)s, %(primary_contact_email_address__c)s, %(program_location_key__c)s,
            %(program_location_type__c)s, %(reggie_account_id__c)s, %(reggie_id__c)s, %(reggie_location_id__c)s,
            %(reggie_name__c)s, %(region__c)s, %(secondary_contact__c)s, %(location_type__c)s,
            %(sibling_discount_amount__c)s, %(sibling_discount_percentage__c)s, %(service_area__c)s,
            %(insurance_expiration_date__c)s, %(former_trade_names__c)s, %(former_legal_entity__c)s,
            %(organization_city__c)s, %(organization_state__c)s, %(partner_program_type__c)s, %(dss_ingestion_timestamp)s
        )
        ON CONFLICT (id)
        DO UPDATE SET
            isdeleted = EXCLUDED.isdeleted,
            masterrecordid = EXCLUDED.masterrecordid,
            name = EXCLUDED.name,
            type = EXCLUDED.type,
            recordtypeid = EXCLUDED.recordtypeid,
            parentid = EXCLUDED.parentid,
            billingstreet = EXCLUDED.billingstreet,
            billingcity = EXCLUDED.billingcity,
            billingstate = EXCLUDED.billingstate,
            billingpostalcode = EXCLUDED.billingpostalcode,
            billingcountry = EXCLUDED.billingcountry,
            billingaddress = EXCLUDED.billingaddress,
            shippingstreet = EXCLUDED.shippingstreet,
            shippingcity = EXCLUDED.shippingcity,
            shippingstate = EXCLUDED.shippingstate,
            shippingpostalcode = EXCLUDED.shippingpostalcode,
            shippingcountry = EXCLUDED.shippingcountry,
            shippingaddress = EXCLUDED.shippingaddress,
            phone = EXCLUDED.phone,
            accountnumber = EXCLUDED.accountnumber,
            website = EXCLUDED.website,
            numberofemployees = EXCLUDED.numberofemployees,
            ownership = EXCLUDED.ownership,
            description = EXCLUDED.description,
            ownerid = EXCLUDED.ownerid,
            createddate = EXCLUDED.createddate,
            createdbyid = EXCLUDED.createdbyid,
            lastmodifieddate = EXCLUDED.lastmodifieddate,
            lastmodifiedbyid = EXCLUDED.lastmodifiedbyid,
            systemmodstamp = EXCLUDED.systemmodstamp,
            lastactivitydate = EXCLUDED.lastactivitydate,
            lastvieweddate = EXCLUDED.lastvieweddate,
            lastreferenceddate = EXCLUDED.lastreferenceddate,
            ispartner = EXCLUDED.ispartner,
            iscustomerportal = EXCLUDED.iscustomerportal,
            channelprogramname = EXCLUDED.channelprogramname,
            channelprogramlevelname = EXCLUDED.channelprogramlevelname,
            chapter_administrator__c = EXCLUDED.chapter_administrator__c,
            chapter_affiliation__c = EXCLUDED.chapter_affiliation__c,
            territory__c = EXCLUDED.territory__c,
            chapter_id__c = EXCLUDED.chapter_id__c,
            membership_offered__c = EXCLUDED.membership_offered__c,
            payments_accepted_in_person__c = EXCLUDED.payments_accepted_in_person__c,
            time_zone__c = EXCLUDED.time_zone__c,
            coach_retention_rate__c = EXCLUDED.coach_retention_rate__c,
            count_account__c = EXCLUDED.count_account__c,
            current_coach_retention_percentage__c = EXCLUDED.current_coach_retention_percentage__c,
            performance_record_type__c = EXCLUDED.performance_record_type__c,
            ys_report_chapter_affiliation__c = EXCLUDED.ys_report_chapter_affiliation__c,
            insurance_expires__c = EXCLUDED.insurance_expires__c,
            affiliate_delivery_partner__c = EXCLUDED.affiliate_delivery_partner__c,
            date_joined__c = EXCLUDED.date_joined__c,
            equipment__c = EXCLUDED.equipment__c,
            graduate__c = EXCLUDED.graduate__c,
            home_school__c = EXCLUDED.home_school__c,
            kindergarten__c = EXCLUDED.kindergarten__c,
            account_id__c = EXCLUDED.account_id__c,
            additional_trade_namechap_affiliation__c = EXCLUDED.additional_trade_namechap_affiliation__c,
            additional_trade_name_logo__c = EXCLUDED.additional_trade_name_logo__c,
            parent_account_id_18__c = EXCLUDED.parent_account_id_18__c,
            account_inactive_date__c = EXCLUDED.account_inactive_date__c,
            legacy_id__c = EXCLUDED.legacy_id__c,
            ein__c = EXCLUDED.ein__c,
            governance_structure__c = EXCLUDED.governance_structure__c,
            youth_population__c = EXCLUDED.youth_population__c,
            contract_effective_date__c = EXCLUDED.contract_effective_date__c,
            active__c = EXCLUDED.active__c,
            chapter_membership_price__c = EXCLUDED.chapter_membership_price__c,
            chapter_standing__c = EXCLUDED.chapter_standing__c,
            contract_expiration_date__c = EXCLUDED.contract_expiration_date__c,
            contract_status__c = EXCLUDED.contract_status__c,
            county__c = EXCLUDED.county__c,
            ho_contracted_location__c = EXCLUDED.ho_contracted_location__c,
            inactive_date__c = EXCLUDED.inactive_date__c,
            legal_entity_name__c = EXCLUDED.legal_entity_name__c,
            membership_active__c = EXCLUDED.membership_active__c,
            membership_discount_amount__c = EXCLUDED.membership_discount_amount__c,
            membership_discount_percentage__c = EXCLUDED.membership_discount_percentage__c,
            membership_end_date__c = EXCLUDED.membership_end_date__c,
            membership_start_date__c = EXCLUDED.membership_start_date__c,
            military_discount_amount__c = EXCLUDED.military_discount_amount__c,
            military_discount_percentage__c = EXCLUDED.military_discount_percentage__c,
            primary_contact_email__c = EXCLUDED.primary_contact_email__c,
            primary_contact__c = EXCLUDED.primary_contact__c,
            primary_contact_email_address__c = EXCLUDED.primary_contact_email_address__c,
            program_location_key__c = EXCLUDED.program_location_key__c,
            program_location_type__c = EXCLUDED.program_location_type__c,
            reggie_account_id__c = EXCLUDED.reggie_account_id__c,
            reggie_id__c = EXCLUDED.reggie_id__c,
            reggie_location_id__c = EXCLUDED.reggie_location_id__c,
            reggie_name__c = EXCLUDED.reggie_name__c,
            region__c = EXCLUDED.region__c,
            secondary_contact__c = EXCLUDED.secondary_contact__c,
            location_type__c = EXCLUDED.location_type__c,
            sibling_discount_amount__c = EXCLUDED.sibling_discount_amount__c,
            sibling_discount_percentage__c = EXCLUDED.sibling_discount_percentage__c,
            service_area__c = EXCLUDED.service_area__c,
            insurance_expiration_date__c = EXCLUDED.insurance_expiration_date__c,
            former_trade_names__c = EXCLUDED.former_trade_names__c,
            former_legal_entity__c = EXCLUDED.former_legal_entity__c,
            organization_city__c = EXCLUDED.organization_city__c,
            organization_state__c = EXCLUDED.organization_state__c,
            partner_program_type__c = EXCLUDED.partner_program_type__c;
            dss_ingestion_timestamp = EXCLUDED.dss_ingestion_timestamp;
        """
        # Prepare the data
        records = [
            {
                "id": account.id,
                "isdeleted": account.isdeleted,
                "masterrecordid": account.masterrecordid,
                "name": account.name,
                "type": account.type,
                "recordtypeid": account.recordtypeid,
                "parentid": account.parentid,
                "billingstreet": account.billingstreet,
                "billingcity": account.billingcity,
                "billingstate": account.billingstate,
                "billingpostalcode": account.billingpostalcode,
                "billingcountry": account.billingcountry,
                "billingaddress": account.billingaddress,
                "shippingstreet": account.shippingstreet,
                "shippingcity": account.shippingcity,
                "shippingstate": account.shippingstate,
                "shippingpostalcode": account.shippingpostalcode,
                "shippingcountry": account.shippingcountry,
                "shippingaddress": account.shippingaddress,
                "phone": account.phone,
                "accountnumber": account.accountnumber,
                "website": account.website,
                "numberofemployees": account.numberofemployees,
                "ownership": account.ownership,
                "description": account.description,
                "ownerid": account.ownerid,
                "createddate": account.createddate,
                "createdbyid": account.createdbyid,
                "lastmodifieddate": account.lastmodifieddate,
                "lastmodifiedbyid": account.lastmodifiedbyid,
                "systemmodstamp": account.systemmodstamp,
                "lastactivitydate": account.lastactivitydate,
                "lastvieweddate": account.lastvieweddate,
                "lastreferenceddate": account.lastreferenceddate,
                "ispartner": account.ispartner,
                "iscustomerportal": account.iscustomerportal,
                "channelprogramname": account.channelprogramname,
                "channelprogramlevelname": account.channelprogramlevelname,
                "chapter_administrator__c": account.chapter_administrator__c,
                "chapter_affiliation__c": account.chapter_affiliation__c,
                "territory__c": account.territory__c,
                "chapter_id__c": account.chapter_id__c,
                "membership_offered__c": account.membership_offered__c,
                "payments_accepted_in_person__c": account.payments_accepted_in_person__c,
                "time_zone__c": account.time_zone__c,
                "coach_retention_rate__c": account.coach_retention_rate__c,
                "count_account__c": account.count_account__c,
                "current_coach_retention_percentage__c": account.current_coach_retention_percentage__c,
                "performance_record_type__c": account.performance_record_type__c,
                "ys_report_chapter_affiliation__c": account.ys_report_chapter_affiliation__c,
                "insurance_expires__c": account.insurance_expires__c,
                "affiliate_delivery_partner__c": account.affiliate_delivery_partner__c,
                "date_joined__c": account.date_joined__c,
                "equipment__c": account.equipment__c,
                "graduate__c": account.graduate__c,
                "home_school__c": account.home_school__c,
                "kindergarten__c": account.kindergarten__c,
                "account_id__c": account.account_id__c,
                "additional_trade_namechap_affiliation__c": account.additional_trade_namechap_affiliation__c,
                "additional_trade_name_logo__c": account.additional_trade_name_logo__c,
                "parent_account_id_18__c": account.parent_account_id_18__c,
                "account_inactive_date__c": account.account_inactive_date__c,
                "legacy_id__c": account.legacy_id__c,
                "ein__c": account.ein__c,
                "governance_structure__c": account.governance_structure__c,
                "youth_population__c": account.youth_population__c,
                "contract_effective_date__c": account.contract_effective_date__c,
                "active__c": account.active__c,
                "chapter_membership_price__c": account.chapter_membership_price__c,
                "chapter_standing__c": account.chapter_standing__c,
                "contract_expiration_date__c": account.contract_expiration_date__c,
                "contract_status__c": account.contract_status__c,
                "county__c": account.county__c,
                "ho_contracted_location__c": account.ho_contracted_location__c,
                "inactive_date__c": account.inactive_date__c,
                "legal_entity_name__c": account.legal_entity_name__c,
                "membership_active__c": account.membership_active__c,
                "membership_discount_amount__c": account.membership_discount_amount__c,
                "membership_discount_percentage__c": account.membership_discount_percentage__c,
                "membership_end_date__c": account.membership_end_date__c,
                "membership_start_date__c": account.membership_start_date__c,
                "military_discount_amount__c": account.military_discount_amount__c,
                "military_discount_percentage__c": account.military_discount_percentage__c,
                "primary_contact_email__c": account.primary_contact_email__c,
                "primary_contact__c": account.primary_contact__c,
                "primary_contact_email_address__c": account.primary_contact_email_address__c,
                "program_location_key__c": account.program_location_key__c,
                "program_location_type__c": account.program_location_type__c,
                "reggie_account_id__c": account.reggie_account_id__c,
                "reggie_id__c": account.reggie_id__c,
                "reggie_location_id__c": account.reggie_location_id__c,
                "reggie_name__c": account.reggie_name__c,
                "region__c": account.region__c,
                "secondary_contact__c": account.secondary_contact__c,
                "location_type__c": account.location_type__c,
                "sibling_discount_amount__c": account.sibling_discount_amount__c,
                "sibling_discount_percentage__c": account.sibling_discount_percentage__c,
                "service_area__c": account.service_area__c,
                "insurance_expiration_date__c": account.insurance_expiration_date__c,
                "former_trade_names__c": account.former_trade_names__c,
                "former_legal_entity__c": account.former_legal_entity__c,
                "organization_city__c": account.organization_city__c,
                "organization_state__c": account.organization_state__c,
                "partner_program_type__c": account.partner_program_type__c, 
                "dss_ingestion_timestamp": datetime.now()  # Capture current timestamp        
            }
             for account in new_raw_account
         ]
         
        # Execute the upsert query for all accounts
        cursor.executemany(upsert_query, records)
        
        #Commit the transaction
        if commit_changes:
            db_connection.commit()
            
        #Close the cursor (but not the connection)
        cursor.close()