CREATE TABLE IF NOT EXISTS ft_ds_raw.validation_errors_sf_badge (
    id TEXT,
    ownerid TEXT,
    isdeleted TEXT,
    name TEXT,
    createddate TEXT,
    lastmodifieddate TEXT,
    lastmodifiedbyid TEXT,
    systemmodstamp TEXT,
    lastvieweddate TEXT,
    lastreferenceddate TEXT,
    description__c TEXT,
    category__c TEXT,
    badge_type__c TEXT,
    is_active__c TEXT,
    points__c TEXT,
    sort_order__c TEXT,
    badge_id__c TEXT,
    age_group__c TEXT,
    dss_ingestion_timestamp TIMESTAMPTZ,
    required_fields_validated BOOLEAN,
    optional_fields_validated BOOLEAN,
    fixed_in_source BOOLEAN
);