CREATE TABLE IF NOT EXISTS sf_session_registration (
    PRIMARY KEY (id, systemmodstamp),
    id TEXT NOT NULL,
    lastmodifieddate TEXT,
    isdeleted TEXT,
    createddate TEXT,
    name TEXT,
    createdbyid TEXT,
    lastmodifiedbyid TEXT,
    systemmodstamp TEXT NOT NULL,
    lastactivitydate TEXT,
    lastvieweddate TEXT,
    lastreferenceddate TEXT,
    listing_session__c TEXT,
    contact__c TEXT,
    allergies__c TEXT,
    amount_paid__c TEXT,
    emergency_contact_email__c TEXT,
    emergency_contact_name__c TEXT,
    emergency_contact_number__c TEXT,
    financial_aid_applied__c TEXT,
    financial_aid__c TEXT,
    membership_registration__c TEXT,
    reevaluate_waitlist__c TEXT,
    reggie_registration_id__c TEXT,
    status__c TEXT,
    trigger_time__c TEXT,
    waitlist_position__c TEXT,
    waitlist_process__c TEXT,
    listing_record_type__c TEXT,
    delete_expired_registration__c TEXT,
    expiration_date__c TEXT,
    bypass_automation__c TEXT,
    count_session_registration__c TEXT,
    parent_contact__c TEXT,
    listing_session_record_type__c TEXT,
    sessiontype_replicated__c TEXT,
    charge_amount__c TEXT,
    cost_difference__c TEXT,
    discount__c TEXT,
    item_price__c TEXT,
    new_listing_session__c TEXT,
    new_session_cost__c TEXT,
    transferred__c TEXT,
    current_session_registration_number__c TEXT,
    dss_ingestion_timestamp TIMESTAMPTZ
);