CREATE TABLE IF NOT EXISTS ft_ds_raw.validation_errors_sf_badge (
    badge_id TEXT,
    owner_id TEXT,
    is_deleted TEXT,
    badge_name TEXT,
    sf_created_timestamp TEXT,
    sf_created_by_id TEXT,
    sf_last_modified_timestamp TEXT,
    sf_last_modified_by_id TEXT,
    sf_system_modstamp TEXT,
    description TEXT,
    category TEXT,
    badge_type TEXT,
    is_active TEXT,
    points TEXT,
    sort_order TEXT,
    external_badge_id TEXT,
    age_group TEXT,
    dss_ingestion_timestamp TIMESTAMPTZ,
    required_fields_validated BOOLEAN,
    optional_fields_validated BOOLEAN,
    fixed_in_source BOOLEAN
);