CREATE TABLE IF NOT EXISTS sf_listing (
    PRIMARY KEY (id, systemmodstamp),
    id TEXT NOT NULL,
    lastmodifieddate TEXT,
    isdeleted TEXT,
    createddate TEXT,
    name TEXT,
    recordtypeid TEXT,
    createdbyid TEXT,
    lastmodifiedbyid TEXT,
    systemmodstamp TEXT NOT NULL,
    lastactivitydate TEXT,
    lastvieweddate TEXT,
    lastreferenceddate TEXT,
    brief_description__c TEXT,
    full_description__c TEXT,
    membership_discount_active__c TEXT,
    military_discount_active__c TEXT,
    presented_by__c TEXT,
    primary_image__c TEXT,
    sibling_discount_active__c TEXT,
    priority__c TEXT,
    ownerid TEXT,
    account__c TEXT,
    class_id__c TEXT,
    class_status__c TEXT,
    end_date__c TEXT,
    event_id__c TEXT,
    event_status__c TEXT,
    external_id__c TEXT,
    hosted_by__c TEXT,
    is_public__c TEXT,
    listing_location_address__c TEXT,
    publish_end_date__c TEXT,
    publish_start_date__c TEXT,
    return_policy__c TEXT,
    start_date__c TEXT,
    total_coaches__c TEXT,
    test__c TEXT,
    count_listing__c TEXT,
	dss_ingestion_timestamp TIMESTAMPTZ
);