CREATE TABLE IF NOT EXISTS ft_ds_raw.validation_errors_sf_contact (
    contact_id_18 TEXT,
    chapter_id TEXT,
    contact_type TEXT,
    age TEXT,
    ethnicity TEXT,
    gender TEXT,
    grade TEXT,
    participation_status TEXT,
    mailing_zip_postal_code TEXT,
    mailing_street TEXT,
    mailing_city TEXT,
    mailing_state TEXT,
    school_name TEXT,
    school_name_other TEXT,
    first_name TEXT,
    last_name TEXT,
    birthdate TEXT,
    household_id TEXT,
    is_deleted TEXT,
    sf_created_timestamp TEXT,
    sf_last_modified_timestamp TEXT,
    sf_system_modstamp TEXT,
    dss_ingestion_timestamp TIMESTAMPTZ,
    required_fields_validated BOOLEAN,
    optional_fields_validated BOOLEAN,
    fixed_in_source BOOLEAN
);