CREATE TABLE IF NOT EXISTS ft_ds_raw.validation_errors_sf_waitlist (
    waitlist_id TEXT,
    waitlist_name TEXT,
    chapter_id TEXT,
    chapter_name TEXT,
    contact TEXT,
    listing_session_location_name TEXT,
    listing_session_name TEXT,
    --membership_end_date TEXT,
    --membership_start_date TEXT,
    --membership_price TEXT,
    --membership_required TEXT,
    parent_contact TEXT,
    status TEXT,
    waitlist_participant_order TEXT,
    waitlist_unique_key TEXT,
    status_is_in_process_or_selected TEXT,
    is_deleted TEXT,
    sf_created_timestamp TEXT,
    sf_last_modified_timestamp TEXT,
    sf_system_modstamp TEXT,
    listing_session TEXT,
    dss_ingestion_timestamp TIMESTAMPTZ,
    required_fields_validated BOOLEAN,
    optional_fields_validated BOOLEAN,
    fixed_in_source BOOLEAN
);