CREATE TABLE IF NOT EXISTS ft_ds_raw.sf_waitlist (
    PRIMARY KEY (id, systemmodstamp),
    id TEXT NOT NULL,
    isdeleted TEXT,
    name TEXT,
    createddate TEXT,
    createdbyid TEXT,
    lastmodifieddate TEXT,
    lastmodifiedbyid TEXT,
    systemmodstamp TEXT NOT NULL,
    lastactivitydate TEXT,
    lastvieweddate TEXT,
    lastreferenceddate TEXT,
    listing_session__c TEXT,
    chapterid__c TEXT,
    chapter_name__c TEXT,
    contact__c TEXT,
    listing_session_location_address__c TEXT,
    listing_session_location_name__c TEXT,
    listing_session_name__c TEXT,
    membership_end_date__c TEXT,
    membership_price__c TEXT,
    membership_required__c TEXT,
    membership_start_date__c TEXT,
    parent_contact__c TEXT,
    status__c TEXT,
    waitlist_participant_order__c TEXT,
    created_by_email__c TEXT,
    waitlist_unique_key__c TEXT,
    status_is_in_process_or_selected__c TEXT,
    dss_ingestion_timestamp TIMESTAMPTZ
);