CREATE TABLE IF NOT EXISTS ft_ds_raw.validation_errors_sf_year_end_participant (
	contact_id TEXT,
	first_name TEXT,
	last_name TEXT,
	program_level TEXT,
	birthdate TEXT,
	age TEXT,
	gender TEXT,
	ethnicity TEXT,
	grade_level TEXT,
	mailing_zip_postal_code TEXT,
	primary_contact_email TEXT,
	email TEXT,
	participation_status TEXT,
	legacy_participant_user_id TEXT,
	school_name TEXT,
	school_name_other TEXT,
	additional_trade_name_account_name TEXT,
	chapter_affiliation_account_name TEXT,
	chapter_id TEXT,
	year TEXT,
    required_fields_validated BOOLEAN,
    optional_fields_validated BOOLEAN,
    fixed_in_source BOOLEAN
);