--based on whole field list
-- CREATE TABLE IF NOT EXISTS ft_ds_refined.sf_contact (
--     contact_id_18,
--     chapter_id,
--     household_id,
--     first_name,
--     last_name,
--     birthdate,
--     age,
--     gender,
--     ethnicity,
--     grade,
--     mailing_street,
--     mailing_city,
--     mailing_state,
--     mailing_zip_postal_code,
--     primary_contacts_email,
--     participant_email,
--     participation_status,
--     school_name,
--     school_name_other,
--     contact_type,
--     emergency_contact_email,
--     emergency_contact_name,
--     emergency_contact_number,
--     primary_contacts_mobile,
--     primary_contacts_name,
--     program_level,
--     snapshot_date
-- );

CREATE TABLE IF NOT EXISTS ft_ds_refined.contact (
    PRIMARY KEY (contact_id_18),
    contact_id_18 CHAR(18),
    chapter_id CHAR(18),
    contact_type VARCHAR(100),
    --age INTEGER,
    ethnicity VARCHAR(100),
    gender VARCHAR(100),
    grade VARCHAR(100),
    participation_status VARCHAR(100),
    mailing_zip_postal_code VARCHAR(20),
    mailing_street VARCHAR(255),
    mailing_city VARCHAR(100),
    mailing_state VARCHAR(100),
    school_name VARCHAR(100),
    school_name_other VARCHAR(255),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    birthdate VARCHAR(100),
    household_id CHAR(18),
    program_level VARCHAR(20),
    is_deleted BOOLEAN,
    sf_created_timestamp TIMESTAMPTZ,
    sf_last_modified_timestamp TIMESTAMPTZ,
    sf_system_modstamp TIMESTAMPTZ,
    dss_ingestion_timestamp TIMESTAMPTZ
);