CREATE TABLE IF NOT EXISTS ft_ds_valid.sf_waitlist (
        PRIMARY KEY (waitlist_id),
        waitlist_id CHAR(18),
        waitlist_name VARCHAR(255),
        chapter_id CHAR(18),
        chapter_name VARCHAR(255),
        contact VARCHAR(255),
        listing_session_location_name VARCHAR(255),
        listing_session_name VARCHAR(255),
        --membership_end_date DATE,
        --membership_start_date DATE,
        --membership_price NUMERIC(4,2),
        --membership_required BOOLEAN,
        parent_contact VARCHAR(255),
        status VARCHAR(255),
        waitlist_participant_order VARCHAR(255),
        waitlist_unique_key VARCHAR(255),
        status_is_in_process_or_selected VARCHAR(255),
        is_deleted BOOLEAN,
        sf_created_timestamp TIMESTAMPTZ,
        sf_last_modified_timestamp TIMESTAMPTZ,
        sf_system_modstamp TIMESTAMPTZ,
        listing_session VARCHAR(255),
        dss_ingestion_timestamp TIMESTAMPTZ
    );