from data_core.salesforce.contact.sf_contact_db_models import SfContactRawDbModel, SfContactSourceModel, map_sf_contact_sources_to_raws
from psycopg2.extensions import connection
from datetime import datetime

from typing import List

import logging

class SalesforceContactDbHelper:

    @staticmethod
    def insert_sf_raw_contacts_from_source_contacts(*,
                                                    db_connection: connection,
                                                    source_contacts: List[SfContactSourceModel],
                                                    commit_changes: bool = True):
        
        SalesforceContactDbHelper.insert_sf_raw_contacts(db_connection = db_connection,
                                                         new_raw_contacts=map_sf_contact_sources_to_raws(source_contacts))

    @staticmethod
    def insert_sf_raw_contacts(*, 
                              db_connection: connection, 
                              new_raw_contacts: List[SfContactRawDbModel],
                              commit_changes: bool = True):
    
        """
        Inserts a collection of SfContactRawDbModel objects into PostgreSQL.
        If a primary key violation occurs, updates the conflicting record.
        
        Args:
        - contacts: List of SfContactRawDbModel instances.
        - conn: A pre-existing psycopg2 connection object.
        """
        # Use the provided connection to create a cursor
        cursor = db_connection.cursor()

        # Define the upsert SQL statement
        upsert_query = """
            INSERT INTO ft_ds_raw.sf_contact 
            (
                id,
                isdeleted,
                accountid,
                lastname,
                firstname,
                salutation,
                "name",
                mailingstreet,
                mailingcity,
                mailingstate,
                mailingpostalcode,
                mailingcountry,
                phone,
                mobilephone,
                homephone,
                email,
                title,
                leadsource,
                birthdate,
                ownerid,
                createddate,
                createdbyid,
                lastmodifieddate,
                lastmodifiedbyid,
                systemmodstamp,
                emailbouncedreason,
                emailbounceddate,
                isemailbounced,
                individualid,
                pronouns,
                genderidentity,
                chapter_affiliation__c,
                chapterid__c,
                active__c,
                ownerid__c,
                contact_type_text__c,
                military__c,
                contact_id__c,
                primary_contact_s_email__c,
                region__c,
                area_of_interest__c,
                attended_coach_advanced_training__c,
                branded_program_location__c,
                casesafeid__c,
                chapter_title__c,
                first_tee_employment_type__c,
                coach_fee_amount_paid__c,
                coach_fee_paid_date__c,
                coach_inactive_date__c,
                coach_level__c,
                inactive__c,
                legacy_id__c,
                school_city__c,
                school_name__c,
                school_name_other__c,
                school_state__c,
                transitioned__c,
                player_coach_training__c,
                total_available_credits__c,
                docebo_is_coach__c,
                request_advanced_training__c,
                participant_level_accomplishments__c,
                coach_membership_fee_due__c,
                coach_membership_fee_paid__c,
                coach_program_start_date__c,
                coach_qualified_for__c,
                coach_retention_status_changed_date__c,
                company__c,
                contact_type__c,
                curriculum_session_registration_date__c,
                custom_created_date__c,
                eligible_participants__c,
                general_availability_days_of_the_week__c,
                general_availability_seasons__c,
                golf_course_affiliation__c,
                how_did_you_hear_about_us__c,
                is_coach__c,
                lead_coach_total_hours__c,
                age__c,
                allergies__c,
                contact_inactive_date__c,
                county__c,
                dietary_restrictions__c,
                disabilities__c,
                emergency_contact_email__c,
                emergency_contact_name__c,
                emergency_contact_number__c,
                request_act_training__c,
                ethnicity__c,
                gender__c,
                lead_coach_total_sessions__c,
                lead_source_other__c,
                listing__c,
                mailing_address_company__c,
                main_program_location__c,
                master_coach_recognition_year__c,
                participation_status__c,
                primary_contact_s_mobile_phone_provider__c,
                primary_contact_s_mobile__c,
                primary_contact_s_name__c,
                program_level__c,
                progressed_participants__c,
                fmp_id__c,
                grade__c,
                legacy_participant_user_id__c,
                mrm_id__c,
                membership_created_date__c,
                membership_status__c,
                membership_valid_from__c,
                membership_valid_to__c,
                mobile_phone_provider__c,
                nickname__c,
                preferred_contact_method__c,
                reggie_id__c,
                reggie_participant_id__c,
                relationship_to_participants__c,
                secondary_email__c,
                work_phone__c,
                progression_status_changed_date__c,
                progression_status__c,
                reason_for_leaving__c,
                recognized_the_first_tee_coach_year__c,
                retained_coach_count__c,
                retention_status__c,
                secondary_contact_s_email__c,
                serve_as_national_trainer__c,
                served_as_one_day_observer__c,
                status__c,
                support_coach_total_coaching_hours__c,
                support_coach_total_sessions__c,
                title__c,
                total_coaching_hours1__c,
                total_listing_sessions_delivered__c,
                total_sessions_coach_assigned__c,
                participant_hours__c,
                parent_contact__c,
                safesport_compliance_not_required__c,
                student_notes__c,
                language__c,
                ft_app_pilot__c,
                international_chapter__c,
                fyi__c,
                impact_today__c,
                press_clippings__c,
                market_size__c,
                territory__c,
                active_chapter__c,
                created_by_lead__c,
                sports_engine_id__c,
                mdr__c,
                merged_email__c,
                mdr_nid__c,
                ethnicity_location__c,
                background_check_exp_bucket__c,
                background_check_expiration_date__c,
                background_check_passed__c,
                background_check_status__c,
                compliant__c,
                days_until_background_check_expires__c,
                days_until_safesport_training_expires__c,
                number_of_safety_records__c,
                safesport_training_completed__c,
                safesport_training_exp_bucket__c,
                safesport_training_expiration_date__c,
                safesport_training_status__c,
                contact_name__c,
                training_type__c,
                chapter_safe_sport_designation__c,
                docebo_email__c,
                docebo_user_id__c,
                docebo_is_community_staff__c,
                docebo_is_parent__c,
                docebo_is_participant__c,
                docebo_is_school_staff__c,
                docebo_username_override__c,
                docebo_username__c,
                salesforce_username__c,
                docebo_pilot_user__c,
                docebo_is_hq_staff__c,
                docebo_disconnect__c,
                docebo_account_active__c,
                master_coach__c,
                primary_contact_home_phone__c,
                impact_today_board_members__c,
                impact_today_coaches__c,
                impact_today_leaders__c,
                nccp__c,
                pursuing_ace__c,
                docebo_is_junior_coach__c,
                lifetime_gamification_points__c,
                respect_in_sport_certification__c,
                docebo_username_randomly_generated__c,
                dss_ingestion_timestamp
            )
            VALUES
            (
                %(id)s,
                %(isdeleted)s,
                %(accountid)s,
                %(lastname)s,
                %(firstname)s,
                %(salutation)s,
                %(name)s,
                %(mailingstreet)s,
                %(mailingcity)s,
                %(mailingstate)s,
                %(mailingpostalcode)s,
                %(mailingcountry)s,
                %(phone)s,
                %(mobilephone)s,
                %(homephone)s,
                %(email)s,
                %(title)s,
                %(leadsource)s,
                %(birthdate)s,
                %(ownerid)s,
                %(createddate)s,
                %(createdbyid)s,
                %(lastmodifieddate)s,
                %(lastmodifiedbyid)s,
                %(systemmodstamp)s,
                %(emailbouncedreason)s,
                %(emailbounceddate)s,
                %(isemailbounced)s,
                %(individualid)s,
                %(pronouns)s,
                %(genderidentity)s,
                %(chapter_affiliation__c)s,
                %(chapterid__c)s,
                %(active__c)s,
                %(ownerid__c)s,
                %(contact_type_text__c)s,
                %(military__c)s,
                %(contact_id__c)s,
                %(primary_contact_s_email__c)s,
                %(region__c)s,
                %(area_of_interest__c)s,
                %(attended_coach_advanced_training__c)s,
                %(branded_program_location__c)s,
                %(casesafeid__c)s,
                %(chapter_title__c)s,
                %(first_tee_employment_type__c)s,
                %(coach_fee_amount_paid__c)s,
                %(coach_fee_paid_date__c)s,
                %(coach_inactive_date__c)s,
                %(coach_level__c)s,
                %(inactive__c)s,
                %(legacy_id__c)s,
                %(school_city__c)s,
                %(school_name__c)s,
                %(school_name_other__c)s,
                %(school_state__c)s,
                %(transitioned__c)s,
                %(player_coach_training__c)s,
                %(total_available_credits__c)s,
                %(docebo_is_coach__c)s,
                %(request_advanced_training__c)s,
                %(participant_level_accomplishments__c)s,
                %(coach_membership_fee_due__c)s,
                %(coach_membership_fee_paid__c)s,
                %(coach_program_start_date__c)s,
                %(coach_qualified_for__c)s,
                %(coach_retention_status_changed_date__c)s,
                %(company__c)s,
                %(contact_type__c)s,
                %(curriculum_session_registration_date__c)s,
                %(custom_created_date__c)s,
                %(eligible_participants__c)s,
                %(general_availability_days_of_the_week__c)s,
                %(general_availability_seasons__c)s,
                %(golf_course_affiliation__c)s,
                %(how_did_you_hear_about_us__c)s,
                %(is_coach__c)s,
                %(lead_coach_total_hours__c)s,
                %(age__c)s,
                %(allergies__c)s,
                %(contact_inactive_date__c)s,
                %(county__c)s,
                %(dietary_restrictions__c)s,
                %(disabilities__c)s,
                %(emergency_contact_email__c)s,
                %(emergency_contact_name__c)s,
                %(emergency_contact_number__c)s,
                %(request_act_training__c)s,
                %(ethnicity__c)s,
                %(gender__c)s,
                %(lead_coach_total_sessions__c)s,
                %(lead_source_other__c)s,
                %(listing__c)s,
                %(mailing_address_company__c)s,
                %(main_program_location__c)s,
                %(master_coach_recognition_year__c)s,
                %(participation_status__c)s,
                %(primary_contact_s_mobile_phone_provider__c)s,
                %(primary_contact_s_mobile__c)s,
                %(primary_contact_s_name__c)s,
                %(program_level__c)s,
                %(progressed_participants__c)s,
                %(fmp_id__c)s,
                %(grade__c)s,
                %(legacy_participant_user_id__c)s,
                %(mrm_id__c)s,
                %(membership_created_date__c)s,
                %(membership_status__c)s,
                %(membership_valid_from__c)s,
                %(membership_valid_to__c)s,
                %(mobile_phone_provider__c)s,
                %(nickname__c)s,
                %(preferred_contact_method__c)s,
                %(reggie_id__c)s,
                %(reggie_participant_id__c)s,
                %(relationship_to_participants__c)s,
                %(secondary_email__c)s,
                %(work_phone__c)s,
                %(progression_status_changed_date__c)s,
                %(progression_status__c)s,
                %(reason_for_leaving__c)s,
                %(recognized_the_first_tee_coach_year__c)s,
                %(retained_coach_count__c)s,
                %(retention_status__c)s,
                %(secondary_contact_s_email__c)s,
                %(serve_as_national_trainer__c)s,
                %(served_as_one_day_observer__c)s,
                %(status__c)s,
                %(support_coach_total_coaching_hours__c)s,
                %(support_coach_total_sessions__c)s,
                %(title__c)s,
                %(total_coaching_hours1__c)s,
                %(total_listing_sessions_delivered__c)s,
                %(total_sessions_coach_assigned__c)s,
                %(participant_hours__c)s,
                %(parent_contact__c)s,
                %(safesport_compliance_not_required__c)s,
                %(student_notes__c)s,
                %(language__c)s,
                %(ft_app_pilot__c)s,
                %(international_chapter__c)s,
                %(fyi__c)s,
                %(impact_today__c)s,
                %(press_clippings__c)s,
                %(market_size__c)s,
                %(territory__c)s,
                %(active_chapter__c)s,
                %(created_by_lead__c)s,
                %(sports_engine_id__c)s,
                %(mdr__c)s,
                %(merged_email__c)s,
                %(mdr_nid__c)s,
                %(ethnicity_location__c)s,
                %(background_check_exp_bucket__c)s,
                %(background_check_expiration_date__c)s,
                %(background_check_passed__c)s,
                %(background_check_status__c)s,
                %(compliant__c)s,
                %(days_until_background_check_expires__c)s,
                %(days_until_safesport_training_expires__c)s,
                %(number_of_safety_records__c)s,
                %(safesport_training_completed__c)s,
                %(safesport_training_exp_bucket__c)s,
                %(safesport_training_expiration_date__c)s,
                %(safesport_training_status__c)s,
                %(contact_name__c)s,
                %(training_type__c)s,
                %(chapter_safe_sport_designation__c)s,
                %(docebo_email__c)s,
                %(docebo_user_id__c)s,
                %(docebo_is_community_staff__c)s,
                %(docebo_is_parent__c)s,
                %(docebo_is_participant__c)s,
                %(docebo_is_school_staff__c)s,
                %(docebo_username_override__c)s,
                %(docebo_username__c)s,
                %(salesforce_username__c)s,
                %(docebo_pilot_user__c)s,
                %(docebo_is_hq_staff__c)s,
                %(docebo_disconnect__c)s,
                %(docebo_account_active__c)s,
                %(master_coach__c)s,
                %(primary_contact_home_phone__c)s,
                %(impact_today_board_members__c)s,
                %(impact_today_coaches__c)s,
                %(impact_today_leaders__c)s,
                %(nccp__c)s,
                %(pursuing_ace__c)s,
                %(docebo_is_junior_coach__c)s,
                %(lifetime_gamification_points__c)s,
                %(respect_in_sport_certification__c)s,
                %(docebo_username_randomly_generated__c)s,
                %(dss_ingestion_timestamp)s
            )
            ON CONFLICT (id, systemmodstamp)
            DO UPDATE SET
                isdeleted = EXCLUDED.isdeleted,
                accountid = EXCLUDED.accountid,
                lastname = EXCLUDED.lastname,
                firstname = EXCLUDED.firstname,
                salutation = EXCLUDED.salutation,
                "name" = EXCLUDED.name,
                mailingstreet = EXCLUDED.mailingstreet,
                mailingcity = EXCLUDED.mailingcity,
                mailingstate = EXCLUDED.mailingstate,
                mailingpostalcode = EXCLUDED.mailingpostalcode,
                mailingcountry = EXCLUDED.mailingcountry,
                phone = EXCLUDED.phone,
                mobilephone = EXCLUDED.mobilephone,
                homephone = EXCLUDED.homephone,
                email = EXCLUDED.email,
                title = EXCLUDED.title,
                leadsource = EXCLUDED.leadsource,
                birthdate = EXCLUDED.birthdate,
                ownerid = EXCLUDED.ownerid,
                createddate = EXCLUDED.createddate,
                createdbyid = EXCLUDED.createdbyid,
                lastmodifieddate = EXCLUDED.lastmodifieddate,
                lastmodifiedbyid = EXCLUDED.lastmodifiedbyid,
                systemmodstamp = EXCLUDED.systemmodstamp,
                emailbouncedreason = EXCLUDED.emailbouncedreason,
                emailbounceddate = EXCLUDED.emailbounceddate,
                isemailbounced = EXCLUDED.isemailbounced,
                individualid = EXCLUDED.individualid,
                pronouns = EXCLUDED.pronouns,
                genderidentity = EXCLUDED.genderidentity,
                chapter_affiliation__c = EXCLUDED.chapter_affiliation__c,
                chapterid__c = EXCLUDED.chapterid__c,
                active__c = EXCLUDED.active__c,
                ownerid__c = EXCLUDED.ownerid__c,
                contact_type_text__c = EXCLUDED.contact_type_text__c,
                military__c = EXCLUDED.military__c,
                contact_id__c = EXCLUDED.contact_id__c,
                primary_contact_s_email__c = EXCLUDED.primary_contact_s_email__c,
                region__c = EXCLUDED.region__c,
                area_of_interest__c = EXCLUDED.area_of_interest__c,
                attended_coach_advanced_training__c = EXCLUDED.attended_coach_advanced_training__c,
                branded_program_location__c = EXCLUDED.branded_program_location__c,
                casesafeid__c = EXCLUDED.casesafeid__c,
                chapter_title__c = EXCLUDED.chapter_title__c,
                first_tee_employment_type__c = EXCLUDED.first_tee_employment_type__c,
                coach_fee_amount_paid__c = EXCLUDED.coach_fee_amount_paid__c,
                coach_fee_paid_date__c = EXCLUDED.coach_fee_paid_date__c,
                coach_inactive_date__c = EXCLUDED.coach_inactive_date__c,
                coach_level__c = EXCLUDED.coach_level__c,
                inactive__c = EXCLUDED.inactive__c,
                legacy_id__c = EXCLUDED.legacy_id__c,
                school_city__c = EXCLUDED.school_city__c,
                school_name__c = EXCLUDED.school_name__c,
                school_name_other__c = EXCLUDED.school_name_other__c,
                school_state__c = EXCLUDED.school_state__c,
                transitioned__c = EXCLUDED.transitioned__c,
                player_coach_training__c = EXCLUDED.player_coach_training__c,
                total_available_credits__c = EXCLUDED.total_available_credits__c,
                docebo_is_coach__c = EXCLUDED.docebo_is_coach__c,
                request_advanced_training__c = EXCLUDED.request_advanced_training__c,
                participant_level_accomplishments__c = EXCLUDED.participant_level_accomplishments__c,
                coach_membership_fee_due__c = EXCLUDED.coach_membership_fee_due__c,
                coach_membership_fee_paid__c = EXCLUDED.coach_membership_fee_paid__c,
                coach_program_start_date__c = EXCLUDED.coach_program_start_date__c,
                coach_qualified_for__c = EXCLUDED.coach_qualified_for__c,
                coach_retention_status_changed_date__c = EXCLUDED.coach_retention_status_changed_date__c,
                company__c = EXCLUDED.company__c,
                contact_type__c = EXCLUDED.contact_type__c,
                curriculum_session_registration_date__c = EXCLUDED.curriculum_session_registration_date__c,
                custom_created_date__c = EXCLUDED.custom_created_date__c,
                eligible_participants__c = EXCLUDED.eligible_participants__c,
                general_availability_days_of_the_week__c = EXCLUDED.general_availability_days_of_the_week__c,
                general_availability_seasons__c = EXCLUDED.general_availability_seasons__c,
                golf_course_affiliation__c = EXCLUDED.golf_course_affiliation__c,
                how_did_you_hear_about_us__c = EXCLUDED.how_did_you_hear_about_us__c,
                is_coach__c = EXCLUDED.is_coach__c,
                lead_coach_total_hours__c = EXCLUDED.lead_coach_total_hours__c,
                age__c = EXCLUDED.age__c,
                allergies__c = EXCLUDED.allergies__c,
                contact_inactive_date__c = EXCLUDED.contact_inactive_date__c,
                county__c = EXCLUDED.county__c,
                dietary_restrictions__c = EXCLUDED.dietary_restrictions__c,
                disabilities__c = EXCLUDED.disabilities__c,
                emergency_contact_email__c = EXCLUDED.emergency_contact_email__c,
                emergency_contact_name__c = EXCLUDED.emergency_contact_name__c,
                emergency_contact_number__c = EXCLUDED.emergency_contact_number__c,
                request_act_training__c = EXCLUDED.request_act_training__c,
                ethnicity__c = EXCLUDED.ethnicity__c,
                gender__c = EXCLUDED.gender__c,
                lead_coach_total_sessions__c = EXCLUDED.lead_coach_total_sessions__c,
                lead_source_other__c = EXCLUDED.lead_source_other__c,
                listing__c = EXCLUDED.listing__c,
                mailing_address_company__c = EXCLUDED.mailing_address_company__c,
                main_program_location__c = EXCLUDED.main_program_location__c,
                master_coach_recognition_year__c = EXCLUDED.master_coach_recognition_year__c,
                participation_status__c = EXCLUDED.participation_status__c,
                primary_contact_s_mobile_phone_provider__c = EXCLUDED.primary_contact_s_mobile_phone_provider__c,
                primary_contact_s_mobile__c = EXCLUDED.primary_contact_s_mobile__c,
                primary_contact_s_name__c = EXCLUDED.primary_contact_s_name__c,
                program_level__c = EXCLUDED.program_level__c,
                progressed_participants__c = EXCLUDED.progressed_participants__c,
                fmp_id__c = EXCLUDED.fmp_id__c,
                grade__c = EXCLUDED.grade__c,
                legacy_participant_user_id__c = EXCLUDED.legacy_participant_user_id__c,
                mrm_id__c = EXCLUDED.mrm_id__c,
                membership_created_date__c = EXCLUDED.membership_created_date__c,
                membership_status__c = EXCLUDED.membership_status__c,
                membership_valid_from__c = EXCLUDED.membership_valid_from__c,
                membership_valid_to__c = EXCLUDED.membership_valid_to__c,
                mobile_phone_provider__c = EXCLUDED.mobile_phone_provider__c,
                nickname__c = EXCLUDED.nickname__c,
                preferred_contact_method__c = EXCLUDED.preferred_contact_method__c,
                reggie_id__c = EXCLUDED.reggie_id__c,
                reggie_participant_id__c = EXCLUDED.reggie_participant_id__c,
                relationship_to_participants__c = EXCLUDED.relationship_to_participants__c,
                secondary_email__c = EXCLUDED.secondary_email__c,
                work_phone__c = EXCLUDED.work_phone__c,
                progression_status_changed_date__c = EXCLUDED.progression_status_changed_date__c,
                progression_status__c = EXCLUDED.progression_status__c,
                reason_for_leaving__c = EXCLUDED.reason_for_leaving__c,
                recognized_the_first_tee_coach_year__c = EXCLUDED.recognized_the_first_tee_coach_year__c,
                retained_coach_count__c = EXCLUDED.retained_coach_count__c,
                retention_status__c = EXCLUDED.retention_status__c,
                secondary_contact_s_email__c = EXCLUDED.secondary_contact_s_email__c,
                serve_as_national_trainer__c = EXCLUDED.serve_as_national_trainer__c,
                served_as_one_day_observer__c = EXCLUDED.served_as_one_day_observer__c,
                status__c = EXCLUDED.status__c,
                support_coach_total_coaching_hours__c = EXCLUDED.support_coach_total_coaching_hours__c,
                support_coach_total_sessions__c = EXCLUDED.support_coach_total_sessions__c,
                title__c = EXCLUDED.title__c,
                total_coaching_hours1__c = EXCLUDED.total_coaching_hours1__c,
                total_listing_sessions_delivered__c = EXCLUDED.total_listing_sessions_delivered__c,
                total_sessions_coach_assigned__c = EXCLUDED.total_sessions_coach_assigned__c,
                participant_hours__c = EXCLUDED.participant_hours__c,
                parent_contact__c = EXCLUDED.parent_contact__c,
                safesport_compliance_not_required__c = EXCLUDED.safesport_compliance_not_required__c,
                student_notes__c = EXCLUDED.student_notes__c,
                language__c = EXCLUDED.language__c,
                ft_app_pilot__c = EXCLUDED.ft_app_pilot__c,
                international_chapter__c = EXCLUDED.international_chapter__c,
                fyi__c = EXCLUDED.fyi__c,
                impact_today__c = EXCLUDED.impact_today__c,
                press_clippings__c = EXCLUDED.press_clippings__c,
                market_size__c = EXCLUDED.market_size__c,
                territory__c = EXCLUDED.territory__c,
                active_chapter__c = EXCLUDED.active_chapter__c,
                created_by_lead__c = EXCLUDED.created_by_lead__c,
                sports_engine_id__c = EXCLUDED.sports_engine_id__c,
                mdr__c = EXCLUDED.mdr__c,
                merged_email__c = EXCLUDED.merged_email__c,
                mdr_nid__c = EXCLUDED.mdr_nid__c,
                ethnicity_location__c = EXCLUDED.ethnicity_location__c,
                background_check_exp_bucket__c = EXCLUDED.background_check_exp_bucket__c,
                background_check_expiration_date__c = EXCLUDED.background_check_expiration_date__c,
                background_check_passed__c = EXCLUDED.background_check_passed__c,
                background_check_status__c = EXCLUDED.background_check_status__c,
                compliant__c = EXCLUDED.compliant__c,
                days_until_background_check_expires__c = EXCLUDED.days_until_background_check_expires__c,
                days_until_safesport_training_expires__c = EXCLUDED.days_until_safesport_training_expires__c,
                number_of_safety_records__c = EXCLUDED.number_of_safety_records__c,
                safesport_training_completed__c = EXCLUDED.safesport_training_completed__c,
                safesport_training_exp_bucket__c = EXCLUDED.safesport_training_exp_bucket__c,
                safesport_training_expiration_date__c = EXCLUDED.safesport_training_expiration_date__c,
                safesport_training_status__c = EXCLUDED.safesport_training_status__c,
                contact_name__c = EXCLUDED.contact_name__c,
                training_type__c = EXCLUDED.training_type__c,
                chapter_safe_sport_designation__c = EXCLUDED.chapter_safe_sport_designation__c,
                docebo_email__c = EXCLUDED.docebo_email__c,
                docebo_user_id__c = EXCLUDED.docebo_user_id__c,
                docebo_is_community_staff__c = EXCLUDED.docebo_is_community_staff__c,
                docebo_is_parent__c = EXCLUDED.docebo_is_parent__c,
                docebo_is_participant__c = EXCLUDED.docebo_is_participant__c,
                docebo_is_school_staff__c = EXCLUDED.docebo_is_school_staff__c,
                docebo_username_override__c = EXCLUDED.docebo_username_override__c,
                docebo_username__c = EXCLUDED.docebo_username__c,
                salesforce_username__c = EXCLUDED.salesforce_username__c,
                docebo_pilot_user__c = EXCLUDED.docebo_pilot_user__c,
                docebo_is_hq_staff__c = EXCLUDED.docebo_is_hq_staff__c,
                docebo_disconnect__c = EXCLUDED.docebo_disconnect__c,
                docebo_account_active__c = EXCLUDED.docebo_account_active__c,
                master_coach__c = EXCLUDED.master_coach__c,
                primary_contact_home_phone__c = EXCLUDED.primary_contact_home_phone__c,
                impact_today_board_members__c = EXCLUDED.impact_today_board_members__c,
                impact_today_coaches__c = EXCLUDED.impact_today_coaches__c,
                impact_today_leaders__c = EXCLUDED.impact_today_leaders__c,
                nccp__c = EXCLUDED.nccp__c,
                pursuing_ace__c = EXCLUDED.pursuing_ace__c,
                docebo_is_junior_coach__c = EXCLUDED.docebo_is_junior_coach__c,
                lifetime_gamification_points__c = EXCLUDED.lifetime_gamification_points__c,
                respect_in_sport_certification__c = EXCLUDED.respect_in_sport_certification__c,
                docebo_username_randomly_generated__c = EXCLUDED.docebo_username_randomly_generated__c,
                dss_ingestion_timestamp = EXCLUDED.dss_ingestion_timestamp
            """
        
         # Prepare the data for the query
        records = [
            {
                "id": contact.id,
                "isdeleted": contact.isdeleted,
                "accountid": contact.accountid,
                "lastname": contact.lastname,
                "firstname": contact.firstname,
                "salutation": contact.salutation,
                "name": contact.name,
                "mailingstreet": contact.mailingstreet,
                "mailingcity": contact.mailingcity,
                "mailingstate": contact.mailingstate,
                "mailingpostalcode": contact.mailingpostalcode,
                "mailingcountry": contact.mailingcountry,
                "phone": contact.phone,
                "mobilephone": contact.mobilephone,
                "homephone": contact.homephone,
                "email": contact.email,
                "title": contact.title,
                "leadsource": contact.leadsource,
                "birthdate": contact.birthdate,
                "ownerid": contact.ownerid,
                "createddate": contact.createddate,
                "createdbyid": contact.createdbyid,
                "lastmodifieddate": contact.lastmodifieddate,
                "lastmodifiedbyid": contact.lastmodifiedbyid,
                "systemmodstamp": contact.systemmodstamp,
                "emailbouncedreason": contact.emailbouncedreason,
                "emailbounceddate": contact.emailbounceddate,
                "isemailbounced": contact.isemailbounced,
                "individualid": contact.individualid,
                "pronouns": contact.pronouns,
                "genderidentity": contact.genderidentity,
                "chapter_affiliation__c": contact.chapter_affiliation__c,
                "chapterid__c": contact.chapterid__c,
                "active__c": contact.active__c,
                "ownerid__c": contact.ownerid__c,
                "contact_type_text__c": contact.contact_type_text__c,
                "military__c": contact.military__c,
                "contact_id__c": contact.contact_id__c,
                "primary_contact_s_email__c": contact.primary_contact_s_email__c,
                "region__c": contact.region__c,
                "area_of_interest__c": contact.area_of_interest__c,
                "attended_coach_advanced_training__c": contact.attended_coach_advanced_training__c,
                "branded_program_location__c": contact.branded_program_location__c,
                "casesafeid__c": contact.casesafeid__c,
                "chapter_title__c": contact.chapter_title__c,
                "first_tee_employment_type__c": contact.first_tee_employment_type__c,
                "coach_fee_amount_paid__c": contact.coach_fee_amount_paid__c,
                "coach_fee_paid_date__c": contact.coach_fee_paid_date__c,
                "coach_inactive_date__c": contact.coach_inactive_date__c,
                "coach_level__c": contact.coach_level__c,
                "inactive__c": contact.inactive__c,
                "legacy_id__c": contact.legacy_id__c,
                "school_city__c": contact.school_city__c,
                "school_name__c": contact.school_name__c,
                "school_name_other__c": contact.school_name_other__c,
                "school_state__c": contact.school_state__c,
                "transitioned__c": contact.transitioned__c,
                "player_coach_training__c": contact.player_coach_training__c,
                "total_available_credits__c": contact.total_available_credits__c,
                "docebo_is_coach__c": contact.docebo_is_coach__c,
                "request_advanced_training__c": contact.request_advanced_training__c,
                "participant_level_accomplishments__c": contact.participant_level_accomplishments__c,
                "coach_membership_fee_due__c": contact.coach_membership_fee_due__c,
                "coach_membership_fee_paid__c": contact.coach_membership_fee_paid__c,
                "coach_program_start_date__c": contact.coach_program_start_date__c,
                "coach_qualified_for__c": contact.coach_qualified_for__c,
                "coach_retention_status_changed_date__c": contact.coach_retention_status_changed_date__c,
                "company__c": contact.company__c,
                "contact_type__c": contact.contact_type__c,
                "curriculum_session_registration_date__c": contact.curriculum_session_registration_date__c,
                "custom_created_date__c": contact.custom_created_date__c,
                "eligible_participants__c": contact.eligible_participants__c,
                "general_availability_days_of_the_week__c": contact.general_availability_days_of_the_week__c,
                "general_availability_seasons__c": contact.general_availability_seasons__c,
                "golf_course_affiliation__c": contact.golf_course_affiliation__c,
                "how_did_you_hear_about_us__c": contact.how_did_you_hear_about_us__c,
                "is_coach__c": contact.is_coach__c,
                "lead_coach_total_hours__c": contact.lead_coach_total_hours__c,
                "age__c": contact.age__c,
                "allergies__c": contact.allergies__c,
                "contact_inactive_date__c": contact.contact_inactive_date__c,
                "county__c": contact.county__c,
                "dietary_restrictions__c": contact.dietary_restrictions__c,
                "disabilities__c": contact.disabilities__c,
                "emergency_contact_email__c": contact.emergency_contact_email__c,
                "emergency_contact_name__c": contact.emergency_contact_name__c,
                "emergency_contact_number__c": contact.emergency_contact_number__c,
                "request_act_training__c": contact.request_act_training__c,
                "ethnicity__c": contact.ethnicity__c,
                "gender__c": contact.gender__c,
                "lead_coach_total_sessions__c": contact.lead_coach_total_sessions__c,
                "lead_source_other__c": contact.lead_source_other__c,
                "listing__c": contact.listing__c,
                "mailing_address_company__c": contact.mailing_address_company__c,
                "main_program_location__c": contact.main_program_location__c,
                "master_coach_recognition_year__c": contact.master_coach_recognition_year__c,
                "participation_status__c": contact.participation_status__c,
                "primary_contact_s_mobile_phone_provider__c": contact.primary_contact_s_mobile_phone_provider__c,
                "primary_contact_s_mobile__c": contact.primary_contact_s_mobile__c,
                "primary_contact_s_name__c": contact.primary_contact_s_name__c,
                "program_level__c": contact.program_level__c,
                "progressed_participants__c": contact.progressed_participants__c,
                "fmp_id__c": contact.fmp_id__c,
                "grade__c": contact.grade__c,
                "legacy_participant_user_id__c": contact.legacy_participant_user_id__c,
                "mrm_id__c": contact.mrm_id__c,
                "membership_created_date__c": contact.membership_created_date__c,
                "membership_status__c": contact.membership_status__c,
                "membership_valid_from__c": contact.membership_valid_from__c,
                "membership_valid_to__c": contact.membership_valid_to__c,
                "mobile_phone_provider__c": contact.mobile_phone_provider__c,
                "nickname__c": contact.nickname__c,
                "preferred_contact_method__c": contact.preferred_contact_method__c,
                "reggie_id__c": contact.reggie_id__c,
                "reggie_participant_id__c": contact.reggie_participant_id__c,
                "relationship_to_participants__c": contact.relationship_to_participants__c,
                "secondary_email__c": contact.secondary_email__c,
                "work_phone__c": contact.work_phone__c,
                "progression_status_changed_date__c": contact.progression_status_changed_date__c,
                "progression_status__c": contact.progression_status__c,
                "reason_for_leaving__c": contact.reason_for_leaving__c,
                "recognized_the_first_tee_coach_year__c": contact.recognized_the_first_tee_coach_year__c,
                "retained_coach_count__c": contact.retained_coach_count__c,
                "retention_status__c": contact.retention_status__c,
                "secondary_contact_s_email__c": contact.secondary_contact_s_email__c,
                "serve_as_national_trainer__c": contact.serve_as_national_trainer__c,
                "served_as_one_day_observer__c": contact.served_as_one_day_observer__c,
                "status__c": contact.status__c,
                "support_coach_total_coaching_hours__c": contact.support_coach_total_coaching_hours__c,
                "support_coach_total_sessions__c": contact.support_coach_total_sessions__c,
                "title__c": contact.title__c,
                "total_coaching_hours1__c": contact.total_coaching_hours1__c,
                "total_listing_sessions_delivered__c": contact.total_listing_sessions_delivered__c,
                "total_sessions_coach_assigned__c": contact.total_sessions_coach_assigned__c,
                "participant_hours__c": contact.participant_hours__c,
                "parent_contact__c": contact.parent_contact__c,
                "safesport_compliance_not_required__c": contact.safesport_compliance_not_required__c,
                "student_notes__c": contact.student_notes__c,
                "language__c": contact.language__c,
                "ft_app_pilot__c": contact.ft_app_pilot__c,
                "international_chapter__c": contact.international_chapter__c,
                "fyi__c": contact.fyi__c,
                "impact_today__c": contact.impact_today__c,
                "press_clippings__c": contact.press_clippings__c,
                "market_size__c": contact.market_size__c,
                "territory__c": contact.territory__c,
                "active_chapter__c": contact.active_chapter__c,
                "created_by_lead__c": contact.created_by_lead__c,
                "sports_engine_id__c": contact.sports_engine_id__c,
                "mdr__c": contact.mdr__c,
                "merged_email__c": contact.merged_email__c,
                "mdr_nid__c": contact.mdr_nid__c,
                "ethnicity_location__c": contact.ethnicity_location__c,
                "background_check_exp_bucket__c": contact.background_check_exp_bucket__c,
                "background_check_expiration_date__c": contact.background_check_expiration_date__c,
                "background_check_passed__c": contact.background_check_passed__c,
                "background_check_status__c": contact.background_check_status__c,
                "compliant__c": contact.compliant__c,
                "days_until_background_check_expires__c": contact.days_until_background_check_expires__c,
                "days_until_safesport_training_expires__c": contact.days_until_safesport_training_expires__c,
                "number_of_safety_records__c": contact.number_of_safety_records__c,
                "safesport_training_completed__c": contact.safesport_training_completed__c,
                "safesport_training_exp_bucket__c": contact.safesport_training_exp_bucket__c,
                "safesport_training_expiration_date__c": contact.safesport_training_expiration_date__c,
                "safesport_training_status__c": contact.safesport_training_status__c,
                "contact_name__c": contact.contact_name__c,
                "training_type__c": contact.training_type__c,
                "chapter_safe_sport_designation__c": contact.chapter_safe_sport_designation__c,
                "docebo_email__c": contact.docebo_email__c,
                "docebo_user_id__c": contact.docebo_user_id__c,
                "docebo_is_community_staff__c": contact.docebo_is_community_staff__c,
                "docebo_is_parent__c": contact.docebo_is_parent__c,
                "docebo_is_participant__c": contact.docebo_is_participant__c,
                "docebo_is_school_staff__c": contact.docebo_is_school_staff__c,
                "docebo_username_override__c": contact.docebo_username_override__c,
                "docebo_username__c": contact.docebo_username__c,
                "salesforce_username__c": contact.salesforce_username__c,
                "docebo_pilot_user__c": contact.docebo_pilot_user__c,
                "docebo_is_hq_staff__c": contact.docebo_is_hq_staff__c,
                "docebo_disconnect__c": contact.docebo_disconnect__c,
                "docebo_account_active__c": contact.docebo_account_active__c,
                "master_coach__c": contact.master_coach__c,
                "primary_contact_home_phone__c": contact.primary_contact_home_phone__c,
                "impact_today_board_members__c": contact.impact_today_board_members__c,
                "impact_today_coaches__c": contact.impact_today_coaches__c,
                "impact_today_leaders__c": contact.impact_today_leaders__c,
                "nccp__c": contact.nccp__c,
                "pursuing_ace__c": contact.pursuing_ace__c,
                "docebo_is_junior_coach__c": contact.docebo_is_junior_coach__c,
                "lifetime_gamification_points__c": contact.lifetime_gamification_points__c,
                "respect_in_sport_certification__c": contact.respect_in_sport_certification__c,
                "docebo_username_randomly_generated__c": contact.docebo_username_randomly_generated__c,
                "dss_ingestion_timestamp": datetime.now()  # Capture current timestamp
            }
            for contact in new_raw_contacts
        ]

        # Execute the upsert query for all contacts
        cursor.executemany(upsert_query, records)

        # Commit the transaction
        if commit_changes:
            db_connection.commit()

        # Close the cursor (but not the connection)
        cursor.close()
